const endeavor_img = '1 x'+imageHTML('images/icons/endeavors', '0.9em;display:inline;opacity:0.8;vertical-allign:bottom')

var texts = {
'Tabard': {'resources':['1 x tela', '1 x órgano'], 'innovation': 'Paint', 'set':['Vagabond']},
'Hard Breastplate': {'resources':['1 x cuero', '1 x hueso'], 'innovation': 'Heat', 'set':['Leather', 'Vagabond']},
'Cloth Leggings': {'resources':['1 x tela', '1 x piel'], 'innovation': 'Ammonia', 'set':['Vagabond']},
'Lion Beast Katar': {'resources':['1 x garra de león', '1 x piel']},
'Claw Head Arrow': {'resources':['1 x garra de león']},
'King Spear': {'resources':['1 x garra de león', '1 x hueso de gran felino']},
'Cat Gut Bow': {'resources':['1 x tendón', '1 x hueso']},
'Cat Fang Knife': {'resources':['1 x dientes de gato anciano', '4 x órgano']},
'White Lion Helm': {'resources':['1 x piel de león blanco', '1 x hueso de gran felino'], 'set':['White Lion']},
'White Lion Gauntlet': {'resources':['1 x piel de león blanco', '1 x hueso'], 'set':['White Lion', 'Brawler']},
'White Lion Coat': {'resources':['1 x piel de león blanco', '1 x piel'], 'set':['White Lion']},
'White Lion Skirt': {'resources':['1 x piel de león blanco', '1 x piel'], 'set':['White Lion']},
'White Lion Boots': {'resources':['1 x piel de león blanco', '1 x piel'], 'set':['White Lion']},
'Cat Eye Circlet': {'resources':['1 x ojo de gato']},
'Whisker Harp': {'resources':['1 x bigotes dorados', '1 x hueso']},
'Lion Headdress': {'resources':['1 x melena brillante']},
'Lion Skin Cloak': {'resources':['2 x piel de león blanco'], 'set':['Brawler']},
'Frenzy Drink': {'resources':['1 x testículos de león']},
'Stone Noses': {'resources':[endeavor_img]},
'Fecal Salve': {'resources':['1 x órgano']},
'Monster Grease': {'resources':['1 x órgano']},
'Dried Acantus': {'resources':['1 x acanto fresco']},
'Lucky Charm': {'resources':['1 x órgano']},
'Monster Tooth Necklace': {'resources':['1 x chatarra', '1 x hueso'], 'innovation': 'Heat'},
'First Aid Kit': {'resources':['1 x cuero', '2 x hueso']},
'Brain Mint': {'resources':['1 x cerebro gritón']},
'Elder Earrings': {'resources':['1 x chatarra', '1 x hueso de caña']},
'Musk Bomb': {'resources':['7 x recursos'], 'innovation': 'Pottery'},
'Scavenger Kit': {'resources':['1 x chatarra', '1 x piel']},
'Bug Trap': {'resources':['1 x encías musculosas', '2 x hueso']},
'Speed Powder': {'resources':['1 x segundo corazón', '2 x órgano']},
'Almanac': {'resources':['2 x cuero'], 'innovation': 'Pictograph'},
'Lantern Sword': {'resources':['1 x hierro', '5 x hueso', '3 x piel']},
'Lantern Dagger': {'resources':['1 x hierro', '4 x cuero', '2 x hueso']},
'Lantern Glaive': {'resources':['2 x hierro', '2 x cuero', '4 x hueso']},
'Dragon Slayer': {'resources':['5 x hierro', '3 x órgano'], 'innovation': 'Paint'},
'Perfect Slayer': {'resources':['9 x hierro', '3 x órgano'], 'innovation': 'Perfect Crucible'},
'Lantern Helm': {'resources':['1 x hierro', '7 x hueso'], 'set':['Lantern']},
'Lantern Gauntlets': {'resources':['2 x hierro', '6 x cuero'], 'set':['Lantern']},
'Lantern Cuirass': {'resources':['2 x hierro', '5 x cuero'], 'set':['Lantern']},
'Lantern Mail': {'resources':['1 x hierro', '5 x órgano'], 'set':['Lantern', 'Warlord']},
'Lantern Greaves': {'resources':['1 x hierro', '5 x cuero'], 'set':['Lantern', 'Warlord']},
'Scrap Shield': {'resources':['3 x hueso', '2 x chatarra', '3 x cuero']},
'Beacon Shield': {'resources':['2 x hierro', '3 x cuero', '4 x hueso']},
'Ring Whip': {'resources':['1 x hierro', '3 x órgano', '3 x hueso']},
'Bone Dagger': {'resources':['1 x hueso']},
'Bone Blade': {'resources':['1 x hueso']},
'Bone Axe': {'resources':['1 x hueso', '1 x órgano']},
'Bone Darts': {'resources':['1 x hueso']},
'Bone Club': {'resources':['3 x hueso']},
'Skull Helm': {'resources':['2 x hueso', '-ó-', '1 x cráneo'], 'set':['Brawler']},
'Bone Pickaxe': {'resources':['1 x hueso', '1 x cuero'], 'innovation': 'Ammonia'},
'Bone Sickle': {'resources':['1 x hueso', '1 x cuero'], 'innovation': 'Ammonia'},
'Dragon Chakram': {'resources':['1 x fragmento de cuerno', '2 x órgano', '1 x cuero']},
'Dragon Bite Bolt': {'resources':['2 x estiércol radiactivo']},
'Talon Knife': {'resources':['2 x garra de rey', '2 x órgano']},
'Nuclear Knife': {'resources':['1 x corazón radiante', '2 x fragmento de cuerno', '2 x chatarra']},
'Núcleo de Poder Rojo': {'resources':['1 x hígado brillante', '1 x hierro']},
'Survivors Lantern': {'resources':[endeavor_img], 'innovation': 'Final Lantern'},
'Rib Blade': {'resources':['1 x costilla carnosa', '1 x piel']},
'Knuckle Shield': {'resources':['1 x mano de mamut', '2 x hueso']},
'Gaxe': {'resources':['1 x hueso denso', '1 x piel gruesa']},
'Greater Gaxe': {'resources':['1 x hueso denso', '1 x manteca gelatinosa']},
'Riot Mace': {'resources':['1 x bulbo puro', '1 x riñón robusto', '1 x manteca gelatinosa', '1 x hueso denso']},
'Gorment Mask': {'resources':['1 x piel gruesa', '1 x cráneo con mano'], 'set':['Gorment']},
'Gorment Sleeves': {'resources':['1 x piel gruesa', '1 x hueso'], 'set':['Gorment']},
'Gorment Suit': {'resources':['3 x piel gruesa', '1 x riñón robusto'], 'set':['Gorment']},
'Gorment Boots': {'resources':['1 x piel gruesa', '1 x hueso'], 'set':['Gorment']},
'Regeneration Suit': {'resources':['1 x revestimiento estomacal', '1 x manteca gelatinosa'], 'set':['Gorment']},
'Pulse Lantern': {'resources':['1 x ojo lechoso', '1 x tiroides activa']},
'Gorn': {'resources':['1 x corazón robusto', '3 x hueso']},
'Armor Spikes': {'resources':['1 x vértebra robusta', '1 x chatarra']},
'Acid Tooth Dagger': {'resources':['1 x glándula ácida', '2 x hueso']},
'Black Sword': {'resources':['1 x gormita', '1 x cráneo con mano']},
'Round Leather Shield': {'resources':['1 x cuero', '1 x hueso', '1 x piel']},
'Hunter Whip': {'resources':['2 x cuero', '1 x hueso']},
'Leather Mask': {'resources':['1 x cuero', '1 x chatarra'], 'set':['Leather']},
'Leather Bracers': {'resources':['1 x cuero', '1 x piel'], 'set':['Leather', 'Vagabond', 'Warlord']},
'Leather Cuirass': {'resources':['1 x cuero', '1 x hueso'], 'set':['Leather', 'Vagabond']},
'Leather Skirt': {'resources':['1 x cuero'], 'set':['Leather', 'Dancer', 'Vagabond']},
'Leather Boots': {'resources':['1 x cuero', '1 x piel'], 'set':['Leather', 'Dancer', 'Vagabond']},
'White Lion Mask': {'resources':[endeavor_img, '1 x melena brillante', '6 x hueso', '4 x órgano']},
'Antelope Mask': {'resources':[endeavor_img, '1 x piel', '6 x hueso', '4 x órgano']},
'Phoenix Mask': {'resources':[endeavor_img, '1 x pluma pequeña', '6 x hueso', '4 x órgano']},
'Death Mask': {'resources':[endeavor_img, '-1 población', '6 x hueso', '4 x órgano']},
'Man Mask': {'resources':[endeavor_img, '1 x cráneo', '6 x hueso', '4 x órgano']},
'God Mask': {'resources':[endeavor_img, '1 x piedra fundadora', '6 x hueso', '4 x órgano']},
 'Feather Shield': {'resources':['2 x plumas pequeñas', '1 x excremento muculento']},
 'Bloom Sphere': {'resources':['1 x parásitos de manos pequeños', '3 x hueso']},
 'Sonic Tomahawk': {'resources':['1 x plumas pequeñas', '1 x chatarra', '1 x hueso de ala hueca']},
 'Hollow Sword': {'resources':['1 x hueso de ala hueca', '2 x hueso', '2 x piel']},
 'Arc Bow': {'resources':['1 x bigote de fénix', '1 x hueso de deseo', '1 x chatarra']},
 'Phoenix Helm': {'resources':['1 x hueso de ala hueca', '1 x plumas pequeñas', '1 x hueso'], 'set':['Phoenix', 'Dancer']},
 'Phoenix Gauntlet': {'resources':['1 x hierro', '1 x cuero', '1 x plumas pequeñas', '1 x hueso'], 'set':['Phoenix']},
 'Phoenix Plackart': {'resources':['1 x hierro', '1 x cuero', '1 x plumas de cola', '1 x piel'], 'set':['Phoenix', 'Warlord']},
 'Phoenix Faulds': {'resources':['1 x hierro', '1 x cuero', '1 x plumas de cola', '1 x órgano'], 'set':['Phoenix', 'Brawler']},
 'Phoenix Greaves': {'resources':['1 x hierro', '1 x cuero', '1 x plumas pequeñas', '1 x órgano'], 'set':['Phoenix', 'Brawler']},
 'Feather Mantle': {'resources':['2 x plumas de cola', '1 x chatarra']},
 'Bird Bread': {'resources':['1 x pústulas', '3 x piel']},
 'Hours Ring': {'resources':['1 x halo brillante', '5 x órganos']},
 'Crest Crown': {'resources':['1 x cresta de fénix', '6 x órganos']},
 'Hollowpoint Arrow': {'resources':['1 x hueso de ala hueca', '1 x chatarra']},
 'Sun Vestments': {'resources':['6 x piel', '1 x bigote dorado', '2 x pústulas']},
 'Sunring Bow': {'resources':['6 x huesos', '1 x bigote de fénix', '1 x vejiga']},
 'Apostle Crown': {'resources':['1 x cuernos legendarios', '1 x cresta de fénix']},
 'Prism Mace': {'resources':['4 x hierro', '1 x halo brillante', '2 x dientes de gato anciano']},
 'Amber Poleaxe': {'resources':['2 x huesos', '1 x órgano', '1 x saco de veneno']},
 'Throwing Knife': {'resources':['1 x seda', '1 x colmillos dentados']},
 'Silk Whip': {'resources':['1 x apéndice grande', '1 x hueso']},
 'Hooded Scrap Katar': {'resources':['2 x apéndice pequeño', '1 x chatarra']},
 'Amber Edge': {'resources':['1 x hueso', '1 x órgano', '1 x quitina']},
 'Silk Turban': {'resources':['1 x sistema nervioso de seda', '3 x seda', '1 x piel'], 'set':['Silk']},
 'Silk Wraps': {'resources':['1 x seda de tela gruesa', '1 x seda'], 'set':['Silk']},
 'Silk Robes': {'resources':['2 x seda', '1 x piel', '1 x exosqueleto'], 'set':['Silk']},
 'Silk Sash': {'resources':['2 x seda', '1 x hueso', '1 x piel'], 'set':['Silk']},
 'Silk Boots': {'resources':['1 x apéndice grande', '1 x seda'], 'set':['Silk']},
 'Body Suit': {'resources':['5 x seda', '2 x piel', '1 x hiladoras']},
 'Silk Bomb': {'resources':['2 x recursos', '2 x seda']},
 'Red Ring': {'resources':['3 x sacos de veneno', '2 x corazones de arácnido'], 'innovation': 'Legless Ball'},
 'Blue Ring': {'resources':['3 x globos oculares', '2 x estóMages'], 'innovation': 'Legless Ball'},
 'Green Ring': {'resources':['3 x patas no puestas', '2 x hilanderas'], 'innovation': 'Legless Ball'},
 'Bandages': {'resources':['1 x piel']},
 'Rawhide Drum': {'resources':['1 x hueso', '1 x piel'], 'innovation': 'Drums'},
 'Rawhide Whip': {'resources':['1 x hueso', '1 x piel'], 'innovation': 'Ammonia'},
 'Rawhide Headband': {'resources':['1 x piel'], 'set':['Rawhide']},
 'Rawhide Gloves': {'resources':['1 x piel'], 'set':['Rawhide']},
 'Rawhide Vest': {'resources':['1 x piel'], 'set':['Rawhide', 'Dancer']},
 'Rawhide Pants': {'resources':['1 x piel'], 'set':['Rawhide']},
 'Rawhide Boots': {'resources':['1 x piel'], 'set':['Rawhide']},
 'Sunspot Dart': {'resources':['1 x piedras solares', '3 x huesos']},
 'Sunshark Bow': {'resources':['2 x enormes dientes solares', '1 x órgano', '1 x hueso de tiburón solar', '1 x sal']},
 'Sunshark Arrows': {'resources':['3 x dientes solares pequeños', '1 x hueso', '1 x aleta de tiburón solar', '1 x sal']},
 'Denticle Axe': {'resources':['1 x mancha solar de 1,000 años', '1 x sal', '1 x lente negra', '1 x hierro', '1 x hueso']},
 'Skleaver': {'resources':['2 x manchas solares de 1,000 años', '1 x sal', '1 x lente negra', '1 x hueso de tiburón solar']},
 'Ink Sword': {'resources':['1 x mancha solar de 3,000 años', '4 x piel', '1 x glándula de tinta de sombra', '1 x hierro']},
 'Cycloid Scale Hood': {'resources':['1 x escamas cíclicas', '1 x piel', '1 x branquias prismáticas'], 'set':['Cycloid Scale']},
 'Cycloid Scale Sleeves': {'resources':['1 x escamas cíclicas', '1 x hueso', '1 x dientes solares pequeños', '1 x sal'], 'set':['Cycloid Scale']},
 'Cycloid Scale Jacket': {'resources':['1 x escamas de cicloide', '1 x chatarra', '1 x enormes dientes solares'], 'set':['Cycloid Scale']},
 'Cycloid Scale Skirt': {'resources':['1 x escamas de cicloide', '1 x piel', '1 x enormes dientes solares'], 'set':['Cycloid Scale']},
 'Cycloid Scale Shoes': {'resources':['1 x escamas de cicloide', '1 x hueso', '1 x tentáculos sombríos'], 'set':['Cycloid Scale']},
 'Sunspot Lantern': {'resources':['2 x piedras solares', '1 x chatarra', '1 x sal']},
 'Quiver and Sunstring': {'resources':['1 x piel interior sombría', '4 x piel', '1 x raíz cerebral', '1 x sal']},
 'Shadow Salvia Shawl': {'resources':['1 x glándula de tinta sombría', '1 x sal', '1 x pulmón fétido', '1 x lengua de tiburón']},
 'Sun Lure and Hook': {'resources':['1 x grasa de tiburón solar', '1 x chatarra']},
 'Sky Harpoon': {'resources':['1 x hueso de tiburón solar', '1 x chatarra', '1 x sal']},
 'Ink Blood Bow': {'resources':['1 x mancha solar de 3.000 años', '5 x órganos', '3 x tentáculos sombríos', '1 x hierro']},
 'Boss Mehndi': {'resources':['1 x bigotes dorados', '1 x hueso']},
 'Beast Knuckle': {'resources':['1 x diente plano grande', '1 x piel']},
 'Red Charm': {'resources':['3 x órganos']},
 'Blood Paint': {'resources':['1 x vejiga', '1 x órgano'], 'innovation': 'Pintura'},
 'Screaming Horns': {'resources':['1 x cuerno en espiral', '1 x chatarra'], 'set':['Screaming', 'Warlord']},
 'Screaming Bracers': {'resources':['1 x piel', '1 x piel'], 'set':['Screaming', 'Dancer']},
 'Screaming Coat': {'resources':['1 x piel', '1 x hueso'], 'set':['Screaming']},
 'Screaming Skirt': {'resources':['1 x piel'], 'set':['Screaming']},
 'Screaming Leg Warmers': {'resources':['1 x piel', '1 x piel'], 'set':['Screaming']},
 'Bone Earrings': {'resources':['1 x hueso de espinilla', '1 x hueso']},
 'Green Charm': {'resources':['3 x órganos']},
 'Blue Charm': {'resources':['3 x órganos']},
 'Lance of Longinus': {'resources':['1 x cuernos legendarios', '6 x órganos']},
 'Counterweighted Axe': {'resources':['2 x hueso', '1 x piel', '1 x órgano']},
 'Whistling Mace': {'resources':['2 x hueso', '1 x órgano']},
 'Zanbato': {'resources':['1 x hueso de gran gato', '2 x piel']},
 'Blood Sheath': {'resources':['5 x órganos', '1 x hueso de ala hueca', '1 x heces muculentas']},
 'Rainbow Katana': {'resources':['1 x pico de ave', '1 x heces arco iris', '1 x hierro', '6 x hueso'], 'innovation': 'Heat'},
 'Skullcap Hammer': {'resources':['2 x hueso', '1 x chatarra']},
 'Scrap Sword': {'resources':['2 x hueso', '1 x chatarra'], 'innovation': 'Heat'},
 'Scrap Dagger': {'resources':['1 x hueso', '1 x chatarra'], 'innovation': 'Heat'},
 'Finger of God': {'resources':['1 x dedo de fénix', '4 x hueso']},
 'DBK Errant Badge': {'resources':['1 x órgano', '1 x hueso']},
 'Rainbow Wing Belt': {'resources':['1 x ala de escarabajo', '1 x órgano', '1 x piel'], 'set':['Rolling']},
 'Digging Claw': {'resources':['1 x uñas de siglo', '2 x chatarra', '2 x recursos']},
 'Seasoned Monster Meat': {'resources':['1 x hongo de placa inferior', '2 x órganos']},
 'Century Shoulder Pads': {'resources':['1 x caparazón de escarabajo', '3 x cuero', '1 x hierro'], 'set':['Rolling']},
 'Scarab Circlet': {'resources':['1 x ojo compuesto', '1 x piel', '1 x hueso'], 'innovation': 'Nightmare Corn', 'set':['Rolling']},
 'Century Greaves': {'resources':['1 x caparazón de escarabajo', '1 x cuerno de escarabajo', '2 x hierro'], 'innovation': 'Nightmare Corn', 'set':['Rolling']},
 'Rubber Bone Harness': {'resources':['1 x hongo de placa inferior', '1 x uñas de siglo', '2 x cuero'], 'innovation': 'Vampiric Artichoke', 'set':['Rolling']},
 'The Beetle Bomb': {'resources':['2 x caparazón de escarabajo', '2 x excremento cáustico conservado', '5 x recursos'], 'innovation': 'Vampiric Artichoke'},
 'Gloom Bracelets': {'resources':['1 x hueso', '1 x cola de león', '1 x chatarra', '1 x agua oscura'], 'innovation': 'Dark Water Research 1'},
 'Gloom-Coated Arrows': {'resources':['2 x hueso', '1 x agua oscura'], 'innovation': 'Dark Water Research 1'},
 'Gloom Mehndi': {'resources':['3 x órganos', '1 x agua oscura'], 'innovation': 'Dark Water Research 1'},
 'Dark Water Vial': {'resources':['1 x órgano', '1 x agua oscura'], 'innovation': 'Dark Water Research 1'},
 'Raptor-Worm Collar': {'resources':['1 x órgano', '1 x chatarra', '1 x agua oscura'], 'innovation': 'Dark Water Research 2'},
 'Gloom Cream': {'resources':['1 x jugo de amor', '1 x piel', '2 x agua oscura'], 'innovation': 'Dark Water Research 2'},
 'Gloom Hammer': {'resources':['3 x cráneo', '1 x hierro', '1 x órgano', '3 x agua oscura'], 'innovation': 'Dark Water Research 2'},
 'Slender Ovule': {'resources':['1 x ojo de fénix', '4 x agua oscura'], 'innovation': 'Dark Water Research 3'},
 'Gloom Katana': {'resources':['1 x hierro', '1 x molde de cristal', '2 x agua oscura'], 'innovation': 'Dark Water Research 3'},
 'Gloom Sheath': {'resources':['1 x hueso de la caña', '2 x órganos', '2 x agua oscura'], 'innovation': 'Dark Water Research 3'},
 'Healing Potion': {'resources':['2 x órganos'], 'roll': '7-12', 'gormchymy':{}},
 'Wisdom Potion': {'resources':['2 x órganos'], 'roll': '13-18', 'gormchymy':{}},
 'Steadfast Potion': {'resources':['2 x órganos'], 'roll': '19-24', 'gormchymy':{}},
 'Power Potion': {'resources':['2 x órganos'], 'roll': '25-30', 'gormchymy':{}},
 'Life Elixir': {'resources':['2 x órganos'], 'roll': '31-36', 'gormchymy':{}},
 'Vespertine Satchel': {'resources':['1 x linterna en flor', '1 x cuero']},
 'Vespertine Foil': {'resources':['1 x brote óseo', '1 x hueso', '1 x chatarra']},
 'Vespertine Cello': {'resources':['1 x brote de linterna', '2 x flores']},
 'Vespertine Arrow': {'resources':['1 x flor']},
 'Vespertine Bow': {'resources':['1 x brote óseo', '1 x brote susurrante', '1 x órgano', '1 x piel']},
 'Ancestral Katana': {'resources':[endeavor_img, '2 x hueso de tiburón sol'], 'innovation': 'Ancestral Katana' },
 'Annointment Oil': {'resources':['2 x piel', '1 x hueso']},
 'Aramis Cape': {'resources':['1 x seda', '1 x piel']},
 'Arena Aegis': {'resources':['1 x cuero', '1 x hueso'], 'set':['Gladiator']},
 'Arena Belt': {'resources':['1 x cuero', '1 x chatarra'], 'set':['Gladiator']},
 'Arena Bracers': {'resources':['1 x cuero', '2 x piel'], 'set':['Gladiator']},
 'Arena Greaves': {'resources':['1 x cuero', '1 x piel'], 'set':['Gladiator']},
 'Arena Helm': {'resources':['1 x hierro', '4 x hueso', '1 x cuero'], 'innovation': 'Blacksmith', 'set':['Gladiator']},
 'Arena Pauldron': {'resources':['1 x cuero', '1 x piel']},
 'Azure Kashaya': {'resources':['2 x seda', '1 x piel'], 'set':['Monk Blue']},
 'Azure Leg Wraps': {'resources':['1 x cuero', '1 x hueso'], 'set':['Monk Blue']},
 'Azure Shroud': {'resources':['1 x seda', '1 x piel'], 'set':['Monk Blue']},
 'Bass Drum': {'resources':['2 x piel', '1 x hueso'], 'innovation': 'Drums'},
 'Blood Bolt': {'resources':['1 x garrapata de pesadilla', '1 x hueso de caña']},
 'Bone Katana': {'resources':['3 x hueso']},
 'Boundless Quiver': {'resources':['1 x cuero', '1 x chatarra']},
 'Caltrops': {'resources':['2 x linterna rota']},
 'Coliseum Mask': {'resources':[endeavor_img, '1 x cráneo entregado', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Concealed Katar': {'resources':['1 x chatarra', '1 x piel'], 'innovation': 'Weapon Crafter'},
'Convalesce Mask': {'resources':[endeavor_img, '1 x hierro', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Cruel Headsman': {'resources':['2 x hueso', '1 x chatarra'], 'innovation': 'Weapon Crafter'},
 'Curse Box': {'resources':['Sacrificar a un sobreviviente con la Maldición del Rey', '-1 población']},
 'Dissection Kit': {'resources':['1 x cuero', '1 x chatarra']},
 'Feral Boots': {'resources':['1 x piel blanca', '1 x diente plano grande'], 'set':['Druid']},
 'Feral Coat': {'resources':['1 x melena reluciente', '1 x piel'], 'set':['Druid']},
 'Feral Faulds': {'resources':['1 x piel'], 'set':['Druid']},
 'Feral Gauntlets': {'resources':['1 x mano curiosa', '1 x garra de león'], 'set':['Druid']},
 'Feral Helm': {'resources':['1 x cuerno espiral', '1 x chatarra'], 'set':['Druid']},
 'Flaying Dagger': {'resources':['2 x hueso', '1 x chatarra'], 'innovation': 'Weapon Crafter'},
 'Ghastly Aegis': {'resources':['1 x cuero', '1 x cascarón', '1 x piel'], 'set':['Necromancer']},
 'Ghastly Bracers': {'resources':['1 x vena cableada', '1 x piel'], 'set':['Necromancer']},
 'Ghastly Exoskeleton': {'resources':['1 x vértebra robusta', '2 x hueso']},
 'Ghastly Greaves': {'resources':['1 x vena cableada', '1 x piel'], 'set':['Necromancer']},
 'Ghastly Shroud': {'resources':['1 x hierro de dragón', '1 x piel'], 'set':['Necromancer']},
 'Ghastly Skirt': {'resources':['1 x ala venosa', '1 x piel'], 'set':['Necromancer']},
 'Gladius': {'resources':['2 x hueso', '1 x chatarra'], 'innovation': 'Weapon Crafter'},
 'Gloom Potion': {'resources':['1 x agua oscura', '1 x tentáculos de sombra']},
 'Grapple Arrow': {'resources':['2 x chatarra', '1 x hueso de espinilla']},
 'Haversack': {'resources':['2 x cuero', '1 x hueso']},
 'Huntsman Mask': {'resources':[endeavor_img, '1 x bigotes dorados', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Infiltrator Boots': {'resources':['1 x piel', '1 x hueso', '1 x agua oscura'], 'set':['Assassin']},
 'Infiltrator Bracers': {'resources':['1 x piel', '1 x agua oscura'], 'set':['Assassin']},
 'Infiltrator Cloak': {'resources':['1 x cerebro chillón', '1 x agua oscura', '1 x piel'], 'set':['Assassin']},
 'Infiltrator Mantle': {'resources':['1 x piel', '1 x chatarra', '1 x agua oscura'], 'set':['Assassin']},
 'Infiltrator Pants': {'resources':['1 x piel', '1 x agua oscura'], 'set':['Assassin']},
 'Iron Fists': {'resources':['1 x chatarra', '2 x hueso']},
 'Madness Mask': {'resources':[endeavor_img, '1 x cerebro chillón', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Magus Digitabulum': {'resources':['1 x ojo de fénix', '1 x piel'], 'set':['Mage']},
 'Magus Excerebro': {'resources':['1 x cerebro chillón', '1 x piel'], 'set':['Mage']},
 'Magus Inferious': {'resources':['1 x órgano', '1 x piel'], 'set':['Mage']},
 'Magus Spectris': {'resources':['1 x branquias prismáticas', '1 x piel'], 'set':['Mage']},
 'Magus Tabernus': {'resources':['2 x piel'], 'set':['Mage']},
 'Masquerade Mask': {'resources':[endeavor_img, '1 x cascarón de escarabajo', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Mengu Mask': {'resources':[endeavor_img, '1 x costillas endurecidas', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Mighty Crossbow': {'resources':['1 x hueso de gran gato', '1 x tendón', '1 x hueso'], 'innovation': 'Weapon Crafter'},
 'Minstrel Boots': {'resources':['1 x seda', '1 x piel', '1 x órganos'], 'set':['Bard']},
 'Minstrel Bracers': {'resources':['1 x seda', '1 x piel'], 'set':['Bard']},
 'Minstrel Hat': {'resources':['1 x seda', '1 x piel', '1 x plumas'], 'set':['Bard']},
 'Minstrel Kilt': {'resources':['1 x seda', '1 x piel', '1 x órganos'], 'set':['Bard']},
 'Minstrel Tunic': {'resources':['1 x seda', '2 x hueso'], 'set':['Bard']},
'Nocturnus Potion': {'resources':['1 x ojo lácteo', '1 x ojo compuesto']},
 'Omen Mask': {'resources':[endeavor_img, '-1 población', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Ordained Breastplate': {'resources':['2 x piel'], 'set':['Cleric']},
 'Ordained Mules': {'resources':['2 x piel'], 'set':['Cleric']},
 'Ordained Shawl': {'resources':['2 x piel'], 'set':['Cleric']},
 'Ordained Vest': {'resources':['2 x piel'], 'set':['Cleric']},
 'Ordained Wrappings': {'resources':['2 x piel'], 'set':['Cleric']},
 'Phoenix Flute': {'resources':['1 x huesos de alas huecas', '1 x piel']},
 'Poison Arrow': {'resources':['1 x pústulas', '1 x hueso de espinilla']},
 'Prayer Beads': {'resources':['1 x ???', '1 x hueso de deseo'], 'innovation': 'Heat'},
 'Prowler Mask': {'resources':[endeavor_img, '2 x acantus frescos', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Radiance Mask': {'resources':[endeavor_img, '2 x escamas ciclóideas', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Righteous Breastplate': {'resources':['2 x hierro', '2 x cuero'], 'set':['Paladin'], 'innovation': 'Blacksmith'},
 'Righteous Gauntlets': {'resources':['2 x hierro', '6 x cuero'], 'set':['Paladin'], 'innovation': 'Blacksmith'},
 'Righteous Greaves': {'resources':['1 x hierro', '5 x cuero'], 'set':['Paladin'], 'innovation': 'Blacksmith'},
 'Righteous Helm': {'resources':['1 x hierro', '7 x hueso'], 'set':['Paladin'], 'innovation': 'Blacksmith'},
 'Righteous Mail': {'resources':['2 x hierro', '1 x cuero', '1 x órgano'], 'set':['Paladin'], 'innovation': 'Blacksmith'},
 'Righteous Shield': {'resources':['1 x chatarra', '1 x piel'], 'innovation': 'Blacksmith'},
 'Rod of Lunacy': {'resources':['1 x raíz cerebral', '1 x hueso'], 'innovation': 'Weapon Crafter'},
 'Rogue Boots': {'resources':['1 x piel', '1 x encías musculosas'], 'set':['Ranger']},
 'Rogue Gauntlets': {'resources':['1 x piel', '1 x encías musculosas'], 'set':['Ranger']},
 'Rogue Shawl': {'resources':['1 x piel', '1 x ojo de gato'], 'set':['Ranger']},
 'Rogue Skirt': {'resources':['1 x piel', '1 x chatarra'], 'set':['Ranger']},
 'Rogue Vest': {'resources':['1 x piel', '1 x hueso'], 'set':['Ranger']},
 'Ronin Dou': {'resources':['1 x cuero', '1 x hueso'], 'set':['Samurai']},
 'Ronin Kabuto': {'resources':['1 x cuero', '2 x chatarra'], 'set':['Samurai']},
 'Ronin Kote': {'resources':['1 x cuero', '1 x piel'], 'set':['Samurai']},
 'Ronin Kusazari': {'resources':['1 x cuero', '1 x piel'], 'set':['Samurai']},
 'Ronin Suneate': {'resources':['1 x cuero', '1 x piel'], 'set':['Samurai']},
 'Sanguine Kashaya': {'resources':['2 x seda', '1 x piel'], 'set':['Monk Red']},
 'Sanguine Leg Wraps': {'resources':['1 x cuero', '1 x hueso'], 'set':['Monk Red']},
 'Sanguine Shroud': {'resources':['1 x seda', '1 x piel'], 'set':['Monk Red']},
 'Seer Mask': {'resources':[endeavor_img, '1 x hierro', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Shadow Boots': {'resources':['1 x piel', '1 x hueso', '1 x agua oscura'], 'set':['Thief']},
 'Shadow Cloak': {'resources':['1 x piel', '1 x órgano', '1 x agua oscura'], 'set':['Thief']},
 'Shadow Gloves': {'resources':['1 x piel', '1 x agua oscura'], 'set':['Thief']},
 'Shadow Shawl': {'resources':['1 x piel', '1 x agua oscura'], 'set':['Thief']},
 'Shadow Skirt': {'resources':['1 x piel', '1 x ojo de fénix', '1 x agua oscura'], 'set':['Thief']},
 'Smoke Bomb': {'resources':['1 x chatarra', '1 x excrementos musculosos']},
 'Spirit Scepter': {'resources':['1 x mano curiosa', '1 x ojo de gato'], 'innovation': 'Weapon Crafter'},
 'Stone Mask': {'resources':[endeavor_img, '1 x piedra fundadora', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'The Assailant': {'resources':['1 x vértebra resistente', '1 x chatarra'], 'innovation': 'Weapon Crafter'},
 'The Executioner': {'resources':['1 x garras del rey', '1 x hueso de gran felino'], 'innovation': 'Weapon Crafter'},
 'The Judge': {'resources':['2 x hueso', '2 x chatarra'], 'innovation': 'Weapon Crafter'},
 'The Jury': {'resources':['1 x cola de león', '1 x garra de león']},
 'The Perpetrator': {'resources':['1 x chatarra', '2 x hueso'], 'innovation': 'The Perpetrator'},
 'The Witness': {'resources':['2 x hueso', '1 x piel', '1 x chatarra'], 'innovation': 'Weapon Crafter'},
 'Thorn Whip': {'resources':['1 x acantus fresco', '1 x hueso']},
 'Twirling Blades': {'resources':['1 x chatarra', '2 x hueso'], 'innovation': 'Weapon Crafter'},
 'Venomous Dagger': {'resources':['1 x glándula ácida', '1 x saco de veneno'], 'innovation': 'Weapon Crafter'},
 'Verdant Kashaya': {'resources':['2 x seda', '1 x piel'], 'set':['Monk Green']},
 'Verdant Leg Wraps': {'resources':['1 x cuero', '1 x hueso'], 'set':['Monk Green']},
 'Verdant Shroud': {'resources':['1 x seda', '1 x piel'], 'set':['Monk Green']},
 'Vigilance Mask': {'resources':[endeavor_img, '1 x hierro', '6 x hueso', '4 x órganos'], 'innovation': 'Mask Maker'},
 'Voodoo Doll': {'resources':['1 x araña cangrejo', '1 x órgano', '1 x ???']},
 'Green Helm': {'resources':['1 x escama', '1 x hierro', '1 x cuerno de escarabajo', '1 x Placa de desviación errante de DBK'], 'innovation': 'Green Helm', 'set':['Green']},
 'Green Gloves': {'resources':['1 x Corazón de cazador', '1 x hierro', '1 x manteca de tocino temblorosa'], 'innovation': 'Green Gloves', 'set':['Green']},
 'Green Plate': {'resources':['1 x Garra izquierda del Caballero León', '2 x hierro', '3 x cuero', '1 x concha de escarabajo'], 'innovation': 'Citrinitas', 'set':['Green']},
 'Green Faulds': {'resources':['1 x elytra', '1 x gormita', '1 x escama', '1 x flor de linterna'], 'innovation': 'Choreia', 'set':['Green']},
 'Green Boots': {'resources':['1 x hierro', '1 x Medalla de Caballero de las Flores', '1 x Grebas calcificadas', '3 x hueso'], 'innovation': 'Forbidden Dance', 'set':['Green']},
 'Griswaldo': {'resources':['1 x gormita', '1 x hierro', '1 x revestimiento de estómago', '1 x Hoja juggernaut calcificada'], 'innovation': 'Griswaldo', 'set':['Green']},
 'Fetorsaurus': {'resources':['1 x Escudo luminoso', '1 x hongo de placa inferior', '1 x flor de virus dormido', '1 x Elixir de vida'], 'innovation': 'Blacksmith', 'set':['Green']},
 'Hooked Claw Knife': {'resources':['1 x garra enganchada', '1 x dientes de gato anciano', '2 x órganos']},
 'Lion Slayer Cape': {'resources':['1 x garra enganchada', '2 x piel blanca', '1 x melena brillante']},
 'Dense Bone Arrows': {'resources':['1 x garra enganchada', '3 x hueso de gran felino', '2 x cuero', '2 x hierro'], 'innovation': 'Blacksmith'},
 'Oxidized Beast Katar': {'resources':[endeavor_img, '1 x Katar de Bestia León', '2 x garra enganchada', '1 x hierro', '3 x cuero', '5 x hueso', '3 x órganos', '1 x liquen negro', '1 x membrana de capullo'], 'innovation': 'Oxidation'},
 'Oxidized Lantern Sword': {'resources':[endeavor_img, '1 x Espada de linterna', '1 x Tubo de linterna', '3 x cuero', '3 x hueso', '3 x órganos', '1 x liquen negro', '1 x membrana de capullo'], 'innovation': 'Oxidation'},
 'Oxidized Beacon Shield': {'resources':[endeavor_img, '1 x Escudo de la baliza', '2 x hierro', '1 x piel', '3 x cuero', '3 x hueso', '3 x órganos', '1 x liquen negro', '1 x membrana de capullo'], 'innovation': 'Oxidation'},
 'Oxidized Lantern Dagger': {'resources':[endeavor_img, '1 x Daga de linterna', '1 x hierro', '4 x piel', '3 x cuero', '3 x hueso', '3 x órganos', '1 x liquen negro', '1 x membrana de capullo'], 'innovation': 'Oxidation'},
 'Oxidized Lantern Glaive': {'resources':[endeavor_img, '1 x Glaive de linterna', '1 x hierro', '3 x cuero', '7 x hueso', '3 x órganos', '1 x liquen negro', '1 x membrana de capullo'], 'innovation': 'Oxidation'},
 'Oxidized Ring Whip': {'resources':[endeavor_img, '1 x Anillo de látigo', '1 x hierro', '3 x cuero', '3 x hueso', '7 x órganos', '1 x liquen negro', '1 x membrana de capullo'], 'innovation': 'Oxidation'},
 'Oxidized Lantern Helm': {'resources':[endeavor_img, '1 x Casco de linterna', '1 x hierro', '3 x cuero', '7 x hueso', '3 x órganos', '1 x liquen negro', '1 x membrana de capullo'], 'innovation': 'Oxidation'},
 'Bronze Cuirass': {'resources':['2 x cobre', '1 x hierro', '2 x cuero'], 'set':['Bronze']},
 'Bronze Gauntlets': {'resources':['2 x cobre', '1 x cuero'], 'set':['Bronze']},
 'Bronze Sword': {'resources':['1 x cobre', '2 x hueso', '1 x cuero'], 'innovation': 'Heat'},
 'Bronze Greaves': {'resources':['2 x cobre', '1 x cuero'], 'set':['Bronze']},
 'Twilight Knight Amulet': {'resources':['1 x cobre', '1 x chatarra'], 'innovation': 'Heat'},
 'Vile Concoction': {'resources':['1 x conducto biliar', '1 x cráneo', '3 x órganos']},
 'Morbid Concoction': {'resources':['1 x tentáculos punzantes', '1 x piel']},
 'Bloated Drinking Bladder': {'resources':['1 x tela exquisita', '2 x órganos']},
 'Drifters Pendant': {'resources':['1 x conducto biliar', '1 x tela exquisita']},
 'Numbing Concoction': {'resources':['1 x tela exquisita', '2 x armadura carnosa']},
 'Psychedelic Concoction': {'resources':['1 x neurotoxina', '2 x tentáculos punzantes'], 'innovation': 'Nightmare Training'},
 'Naginata': {'resources':['1 x barba destruida', '1 x piel sedosa', '2 x hueso'], 'innovation': 'Weapon Crafter'},
 'Iron Parasol': {'resources':['1 x placa petrificada', '1 x cuero', '2 x hierro'], 'innovation': 'Blacksmith'},
}

module.exports = {
 texts,
}
