const event_img = imageHTML('images/icons/book', '0.9em;display:inline;vertical-allign:bottom')

const texts = {
'Cabled Vein': {'label':'', 'group_name':'Rey Dragón', 'type': 'órgano', 'text': '<i>Un denso conjunto de tubos sangrientos.</i><br /><br />Probabilidad de obtención: 2/21.'},
'Dragon Iron': {'type': 'hierro', 'group_name':'Rey Dragón', 'text': '<i>Se siente pesado, pero cuando se suelta, cae tan lentamente como una pluma.</i><br /><br />Probabilidad de obtención: 1/21.'},
'Hardened Ribs': {'type': 'hueso', 'group_name':'Rey Dragón', 'text': '<i>Fuertes, flexibles y huecos.</i><br /><br />Probabilidad de obtención: 1/21.'},
'Horn Fragment': {'type': 'hueso', 'group_name':'Rey Dragón', 'text': '<i>Las palabras cercanas hacen que resuenen.</i><br /><br />Probabilidad de obtención: 4/21.'},
'Husk': {'type': 'piel', 'group_name':'Rey Dragón', 'text': '<i>Una capa en descomposición de piel anterior.</i><br /><br />Probabilidad de obtención: 3/21.'},
'Kings Claws': {'label':'Garras del Rey', 'type': 'hueso', 'group_name':'Rey Dragón', 'text': '<i>Alarmantemente cálidas y lo suficientemente afiladas como para hacer sangrar con un toque.</i><br /><br />Probabilidad de obtención: 4/21.'},
'Kings Tongue': {'label':'Lengua del Rey', 'type': 'piel', 'group_name':'Rey Dragón', 'text': '<i>Suave, seca y afilada.</i><br /><br />Probabilidad de obtención: 1/21.'},
'Radioactive Drug': {'type': 'órgano/desperdicio', 'group_name':'Rey Dragón', 'text': '<i>Desprende humo con un olor acre.</i><br /><br />Probabilidad de obtención: 2/21.'},
'Veined Wing': {'type': 'piel', 'group_name':'Rey Dragón', 'text': '<i>La sangre gotea constantemente de ella.</i><br /><br />Probabilidad de obtención: 3/21.'},

'Beetle Horn': {'type': 'hueso', 'group_name':'Caballero del Escarabajo de Estiércol', 'text': '<b>Estimulación cerebral</b> <i style="color:#999">(requiere Escarificación)</i><br />Archivo y Tiro de <b>1d10</b>:<br /> <b style=\"color:#cc0;\">1-4</b><div style="font-size:0.9em;display: inline;"> - Tu cerebro es perforado y mueres.</div><br /> <b style=\"color:#cc0;\">5+</b><div style="font-size:0.9em;display: inline;"> - Obtienes los beneficios de la <b>Edad 1</b> y la <b>Edad 2</b> sin ganar PX de Caza. La Estimulación Cerebral ignora la regla de "una vez en la vida" en la '+event_img+'<b>Edad</b>.</div><br /><br />Probabilidad de obtención: 1/11.'},
'Century Fingernails': {'type': 'hueso', 'group_name':'Caballero del Escarabajo de Estiércol', 'text': '<i>Estas uñas nunca se cortan. En cambio, se doblan y martillean cientos de veces hasta obtener un filo imposiblemente fino.</i><br /><br />Probabilidad de obtención: 2/11.'},
'Century Shell': {'type': 'piel/hierro', 'group_name':'Caballero del Escarabajo de Estiércol', 'text': '<i>Esta placa de armadura antigua y rica en minerales está cubierta de arañazos de viento cortante.</i><br /><br />Puedes gastar esto como si fuera un recurso de Caparazón de Escarabajo.<br /><br />Probabilidad de obtención: 1/11.'},
'Compound Eye': {'type': 'órgano/consumible', 'group_name':'Caballero del Escarabajo de Estiércol', 'text': '<i>Un conjunto de ojos de diferentes colores, cada uno lleno de un jarabe cremoso y agridulce.</i><br /><br />Si tienes 3+ coraje, puedes consumirlo y archivarlo para ganar +3d10 de locura.<br /><br />Probabilidad de obtención: 1/11.'},
'Elytra': {'type': 'hueso/piel/órgano', 'group_name':'Caballero del Escarabajo de Estiércol', 'text': '<i>La parte inferior acanalada de estas conchas grandes es una superficie ideal para afilar armas.</i><br /><br />Un sobreviviente puede archivar esto para que todos sus ataques en el próximo enfrentamiento sean Afilados.<br /><br />Probabilidad de obtención: 1/11.'},
'Scarab Shell': {'type': 'piel', 'group_name':'Caballero del Escarabajo de Estiércol', 'text': '<i>Fresco y aceitoso al tacto. La luz de la linterna revela una brillante banda de colores bailando en su superficie.</i><br /><br />Probabilidad de obtención: 3/11.'},
'Scarab Wing': {'type': 'órgano', 'group_name':'Caballero del Escarabajo de Estiércol', 'text': '<i>Cuando se empapan en agua, estas alas llenas de venas ganan cierta elasticidad.</i><br /><br />Probabilidad de obtención: 1/11.'},
'Underplate Fungus': {'type': 'hierba/piel/consumible', 'group_name':'Caballero del Escarabajo de Estiércol', 'text': '<i>Un hongo en forma de sacacorchos que crece en los canales vacíos entre las placas de armadura del Caballero del Escarabajo de Estiércol.</i><br /><br />Probabilidad de obtención: 1/11.'},

'Lantern Bloom': {'type': 'flor/piel', 'group_name':'Caballero de las Flores', 'text': '<b>Perecedero</b>.<br />Puedes <b>consumir</b> y archivar esto durante el enfrentamiento para ganar +3 fichas de suerte, -1 suerte permanente y el trastorno <b>Adicción a las Flores</b>.<br /><br />Probabilidad de obtención: 3/14.'},
'Lantern Bud': {'type': 'flor/desperdicio', 'group_name':'Caballero de las Flores', 'text': '<b>Perecedero</b>.<br />Puedes <b>consumir</b> y archivar esto durante la fase de asentamiento para ganar +3{image@images/icons/endeavors}, saltar la próxima caza y obtener el trastorno <b>Adicción a las Flores</b>.<br /><br />Probabilidad de obtención: 1/14.'},
'Osseous Bloom': {'type': 'flor/hueso', 'group_name':'Caballero de las Flores', 'text': '<b>Perecedero</b>.<br />Puedes <b>consumir</b> y archivar esto durante el enfrentamiento para eliminar todas tus fichas de sangrado y fichas de atributo negativas y obtener el trastorno <b>Adicción a las Flores</b>.<br /><br />Probabilidad de obtención: 5/14.'},
'Sighing Bloom': {'type': 'flor/órgano', 'group_name':'Caballero de las Flores', 'text': '<b>Perecedero</b>.<br />Puedes <b>consumir</b> y archivar esto durante el enfrentamiento para ganar 3 supervivencia, 3 locura y el trastorno <b>Adicción a las Flores</b>.<br /><br />Probabilidad de obtención: 3/14.'},
'Warbling Bloom': {'type': 'flor/piel', 'group_name':'Caballero de las Flores', 'text': '<b>Perecedero</b>.<br />Puedes plantar esto durante la fase de asentamiento para archivarlo y ganar +1 población. El superviviente nacido con el trastorno <b>Adicción a las Flores</b> y una cara igual que la del Warbling Bloom.<br /><br />Probabilidad de obtención: 2/14.'},

'Acid Gland': {'type': 'órgano', 'group_name':'Gorm', 'text': '<i>Derrite la piel.</i><br /><br />Probabilidad de obtención: 1/21.'},
'Dense Bone': {'type': 'hueso', 'group_name':'Gorm', 'text': '<i>Robusto.</i><br /><br />Probabilidad de obtención: 2/21.'},
'Gorm Brain': {'type': 'órgano', 'group_name':'Gorm', 'text': '<i>Sorprendentemente pequeño.</i><br /><br />Probabilidad de obtención: 1/21.'},
'Handed Skull': {'type': 'hueso', 'group_name':'Gorm', 'text': '<i>Incomparablemente denso.</i><br /><br />Probabilidad de obtención: 1/21.'},
'Jiggling Lard': {'type': 'órgano/piel', 'group_name':'Gorm', 'text': '<i>Masa espesa y temblorosa.</i><br /><br />Probabilidad de obtención: 2/21.'},
'Mammoth Hand': {'type': 'hueso/piel/órgano', 'group_name':'Gorm', 'text': '<i>Un guante enorme y de cuero.</i><br /><br />Probabilidad de obtención: 2/21.'},
'Meaty Rib': {'type': 'hueso/órgano', 'group_name':'Gorm', 'text': '<i>Útil y delicioso.</i><br /><br />Probabilidad de obtención: 2/21.'},
'Milky Eye': {'type': 'órgano', 'group_name':'Gorm', 'text': '<i>Cuando se obtiene este recurso, selecciona a un superviviente para que gane +3 de locura.<br /><br />Probabilidad de obtención: 1/21.'},
'Stout Heart': {'type': 'órgano', 'group_name':'Gorm', 'text': '<i>Una bomba titánica.</i><br /><br />Probabilidad de obtención: 2/21.'},
'Stout Hide': {'type': 'piel', 'group_name':'Gorm', 'text': '<i>Piel arrugada al tacto.</i><br /><br />Probabilidad de obtención: 4/21.'},
'Stout Kidney': {'type': 'órgano', 'group_name':'Gorm', 'text': '<b>Consumir</b>: archiva esto y tira 1d10:<br /> <b style=\"color:#cc0;\">1-5</b><div style="font-size:0.9em;display: inline;"> - reduce tu supervivencia a 0.</div><br /><b style=\"color:#cc0;\">6+</b><div style="font-size:0.9em;display: inline;"> - gana 10 supervivencia.</div><br /><br />Probabilidad de obtención: 2/21.'},
'Stout Vertebrae': {'type': 'hueso', 'group_name':'Gorm', 'text': '<i>Macizo y intrincadamente unido.</i><br /><br />Probabilidad de obtención: 1/21.'},

'Bird Beak': {'type': 'hueso', 'group_name':'Fénix', 'text': '<i>Sorprendentemente dentado.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Black Skull': {'type': 'hierro/cráneo/hueso', 'group_name':'Fénix', 'text': '<i>Envejecido a la perfección.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Hollow Wing Bones': {'type': 'hueso', 'group_name':'Fénix', 'text': '<i>Delicados y finamente equilibrados.</i><br /><br />Probabilidad de obtención: 3/24.'},
'Muculent Droppings': {'type': 'órgano', 'group_name':'Fénix', 'text': '<i>Con un aroma delicado, cáscara papiracea.</i><br /><br />Probabilidad de obtención: 3/24.'},
'Phoenix Eye': {'type': 'órgano/desperdicio', 'group_name':'Fénix', 'text': '<i>Lleno de un líquido espeso y metálico.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Phoenix Finger': {'type': 'hueso', 'group_name':'Fénix', 'text': 'Cuando obtienes esto, un superviviente de tu elección gana +3 de locura.<br /><br />Probabilidad de obtención: 2/24.'},
'Phoenix Whisker': {'type': 'piel', 'group_name':'Fénix', 'text': '<i>Suave, pero resistente.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Pustules': {'type': 'órgano/consumible', 'group_name':'Fénix', 'text': '<i>El aroma es tentador.</i><br /><br />Probabilidad de obtención: 2/24.'},
'Rainbow Droppings': {'type': 'órgano/consumible', 'group_name':'Fénix', 'text': '<b>Consumir</b>: Archiva esto y tira 1d10:<br /><b style=\"color:#cc0;\">1-6</b><div style="font-size:0.9em;display: inline;"> - tu corazón explota, matándote al instante.</div><br /><b style=\"color:#cc0;\">7+</b><div style="font-size:0.9em;display: inline;"> - gana +1 velocidad permanente.</div><br /><br />Probabilidad de obtención: 1/24.'},
'Shimmering Halo': {'type': 'órgano', 'group_name':'Fénix', 'text': '<i>Curiosamente pesado.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Small Feathers': {'type': 'piel', 'group_name':'Fénix', 'text': '<i>Interior suave con bordes afilados como cuchillas.</i><br /><br />Probabilidad de obtención: 3/24.'},
'Small Hand Parasites': {'type': 'órgano', 'group_name':'Fénix', 'text': '<i>Todavía se retuercen.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Tail Feathers': {'type': 'piel', 'group_name':'Fénix', 'text': '<i>Más ligero que el aire.</i><br /><br />Probabilidad de obtención: 3/24.'},
'Wishbone': {'type': 'hueso', 'group_name':'Fénix', 'text': '<i>Un hueso delicado con una extraña aura.</i><br /><br />Probabilidad de obtención: 1/24.'},

'Beast Steak': {'type': 'órgano/consumible', 'group_name':'Antílope Gritón', 'text': '<i>Increíblemente apetitoso.</i><br /><br />Probabilidad de obtención: 2/16.'},
'Bladder': {'type': 'órgano/consumible', 'group_name':'Antílope Gritón', 'text': '<i>Huele a orina.</i><br /><br />Probabilidad de obtención: 1/16.'},
'Large Flat Tooth': {'type': 'hueso', 'group_name':'Antílope Gritón', 'text': '<i>Su superficie es áspera y rugosa.</i><br /><br />Cuando obtienes esto, un superviviente de tu elección gana +1 de locura.<br /><br />Probabilidad de obtención: 2/16.'},
'Muscly Gums': {'type': 'órgano/consumible', 'group_name':'Antílope Gritón', 'text': '<i>Difíciles de separar.</i><br /><br />Probabilidad de obtención: 1/16.'},
'Pelt': {'type': 'piel', 'group_name':'Antílope Gritón', 'text': '<i>Áspera y cálida al tacto.</i><br /><br />Probabilidad de obtención: 4/16.'},
'Screaming Brain': {'type': 'órgano/consumible', 'group_name':'Antílope Gritón', 'text': '<b>Consumir</b>: Archiva esto y gana supervivencia hasta el límite actual.<br /><br />Probabilidad de obtención: 1/16.'},
'Shank Bone': {'type': 'hueso', 'group_name':'Antílope Gritón', 'text': '<i>Extrañamente articulado.</i><br /><br />Probabilidad de obtención: 4/16.'},
'Spiral Horn': {'type': 'hueso', 'group_name':'Antílope Gritón', 'text': '<i>Gime lastimosamente cuando se sopla.</i><br /><br />Probabilidad de obtención: 1/16.'},

'Arachnid Heart': {'type': 'órgano', 'group_name':'Spidicules', 'text': '<i>Frio al tacto, incluso cuando recién se extrae.</i><br /><br />Probabilidad de obtención: 1/14.'},
'Chitin': {'type': 'piel', 'group_name':'Spidicules', 'text': '<i>Una cáscara escamosa y amarga al olor.</i><br /><br />Probabilidad de obtención: 1/14.'},
'Exoskeleton': {'type': 'piel', 'group_name':'Spidicules', 'text': '<i>Placas maleables e interconectadas.</i><br /><br />Probabilidad de obtención: 1/14.'},
'Eyeballs': {'type': 'órgano', 'group_name':'Spidicules', 'text': '<i>Cada uno apunta en una dirección diferente.</i><br /><br />Probabilidad de obtención: 1/14.'},
'Large Appendage': {'type': 'hueso', 'group_name':'Spidicules', 'text': '<i>Podría ser útil.</i><br /><br />Probabilidad de obtención: 2/14.'},
'Serrated Fangs': {'type': 'hueso', 'group_name':'Spidicules', 'text': '<b>Elevaciones con Cuchilla</b> <i style="color:#999">(requiere Entrenamiento en Pesadillas)</i> - Tira 1d10<br /><b style=\"color:#cc0;\">1-3</b><div style="font-size:0.9em;display: inline;"> - Gana un trastorno aleatorio.</div><br /><b style=\"color:#cc0;\">4+</b><div style="font-size:0.9em;display: inline;"> - Gana +1 Fuerza permanente. <i>Las elevaciones con cuchilla se destruyen;</i> archiva esta carta.</div><br /><br />Probabilidad de obtención: 1/14.'},
'Small Appendages': {'type': 'piel', 'group_name':'Spidicules', 'text': '<i>Las manos internas parecen sorprendentemente humanas.</i><br /><br />Probabilidad de obtención: 2/14.'},
'Spinnerets': {'type': 'órgano/desperdicio', 'group_name':'Spidicules', 'text': '<i>Más complejos que cualquier dispositivo.</i><br /><br />Probabilidad de obtención: 1/14.'},
'Stomach': {'type': 'órgano', 'group_name':'Spidicules', 'text': '<b>Consumir</b>: Archiva esta carta para ganar +1 XP de Caza.<br /><br />Probabilidad de obtención: 1/14.'},
'Thick Web Silk': {'type': 'seda/piel', 'group_name':'Spidicules', 'text': '<i>Imposible de perforar.</i><br /><br />Probabilidad de obtención: 1/14.'},
'Unlaid Eggs': {'type': 'órgano/consumible', 'group_name':'Spidicules', 'text': 'Durante la fase de asentamiento, puedes <b>consumir</b> y archivar estos pequeños huevos deliciosos para ganar 10 de supervivencia.<br /><br />Probabilidad de obtención: 1/14.'},
'Venom Sac': {'type': 'órgano/consumible', 'group_name':'Spidicules', 'text': '<b>Consumir</b>: Archiva esta carta y tira 1d10.<br /><b style=\"color:#cc0;\">1-5</b><div style="font-size:0.9em;display: inline;"> - mueres instantáneamente.</div><br /><b style=\"color:#cc0;\">6+</b><div style="font-size:0.9em;display: inline;"> - obtén el Arte de Combate Secreto <b>Toque de la Muerte</b>.</div><br /><br />Probabilidad de obtención: 1/14.'},

'Black Lens': {'type': 'órgano', 'group_name':'Sunstalker', 'text': '<i>Estos ojos están llenos de una sustancia sabrosa y pegajosa que se seca cuando se expone al aire.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Brain Root': {'type': 'órgano', 'group_name':'Sunstalker', 'text': '<i>Los hilos de la raíz son fuertes y elásticos. La carne de arriba es inútil.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Cycloid Scales': {'type': 'piel', 'group_name':'Sunstalker', 'text': '<i>Extremadamente reflectantes y coloridas.</i><br /><br />Probabilidad de obtención: 5/24.'},
'Fertility Tentacle': {'type': 'órgano', 'group_name':'Sunstalker', 'text': '<i>Este apéndice en forma de tubo tiene una cavidad en la base que almacena huevos.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Huge Sunteeth': {'type': 'hueso', 'group_name':'Sunstalker', 'text': '<i>Estos dientes resistentes pero ligeros están hechos de cientos de capas finas de hueso, separadas por hileras de tallos dicotiledóneos.</i><br /><br />Probabilidad de obtención: 3/24.'},
'Inner Shadow Skin': {'type': 'piel', 'group_name':'Sunstalker', 'text': '<i>Este material suave pero gomoso bloquea la luz.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Prismatic Gills': {'type': 'órgano', 'group_name':'Sunstalker', 'text': '<i>Cuando obtienes esto, obtén el trastorno Sin Emoción. Las branquias emiten un rastro de color borroso.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Shadow Ink Gland': {'type': 'órgano', 'group_name':'Sunstalker', 'text': '<i>La tinta se puede usar para pintar sombras que desaparecen a la luz de la linterna.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Shadow Tentacles': {'type': 'órgano/piel', 'group_name':'Sunstalker', 'text': '<i>Cuando obtienes esto durante la caza o el enfrentamiento, devuélvelo al mazo de recursos y vuelve a robar si algún superviviente está <b>ciego</b>.</i><br /><br />Probabilidad de obtención: 2/24.'},

'Shark Tongue': {'type': 'órgano', 'group_name':'Sunstalker', 'text': '<i>¡Tan resbaladiza que es difícil de sostener!</i><br /><br />Probabilidad de obtención: 1/24.'},
'Small Sunteeth': {'type': 'hueso', 'group_name':'Sunstalker', 'text': '<i>A diferencia de los grandes sunteeth, estos son extremadamente afilados y limpios.</i><br /><br />Probabilidad de obtención: 3/24.'},
'Stink Lung': {'type': 'órgano', 'group_name':'Sunstalker', 'text': '<i>Cuando se aprieta, emerge un ruido divertido seguido de un aroma tentador.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Sunshark Blubber': {'type': 'órgano', 'group_name':'Sunstalker', 'text': '<i>Cuando se infla con aire, esta grasa flota suavemente.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Sunshark Bone': {'type': 'hueso', 'group_name':'Sunstalker', 'text': '<i>El centro está lleno de agua.</i><br /><br />Probabilidad de obtención: 1/24.'},
'Sunshark Fin': {'type': 'hueso/piel', 'group_name':'Sunstalker', 'text': '<i>Al quitar las manos viscosas se revela una sustancia viscosa curable.</i><br /><br />Probabilidad de obtención: 1/24.'},

'Curious Hand': {'image':'true', 'group_name':'León Blanco', 'type': 'piel', 'text': ' <i>Sostener esto te llena de tristeza.</i><br /><br />Cuando obtienes esto, un superviviente aleatorio gana +1 insanidad.<br /><br />Probabilidad de obtención: 1/19.'},
'Eye of Cat': {'image':'true', 'group_name':'León Blanco', 'type': 'órgano/consumible', 'text': '<i>Un ojo perfectamente conservado.</i><br /><br />Probabilidad de obtención: 1/19.'},
'Golden Whiskers': {'image':'true', 'group_name':'León Blanco', 'type': 'órgano', 'text': '<i>¡Estos bigotes son resistentes!</i><br /><br />Probabilidad de obtención: 1/19.'},
'Great Cat Bones': {'image':'true', 'group_name':'León Blanco', 'type': 'hueso', 'text': '<i>Fuertes y sorprendentemente ligeros.</i><br /><br />Probabilidad de obtención: 4/19.'},
'Lion Claw': {'image':'true', 'group_name':'León Blanco', 'type': 'hueso', 'text': '<i>Una garra afilada y retráctil.</i><br /><br />Probabilidad de obtención: 3/19.'},
'Lion Tail': {'image':'true', 'group_name':'León Blanco', 'type': 'piel', 'text': '<i>Es sorprendentemente pesado.</i><br /><br />Probabilidad de obtención: 1/19.'},
'Lion Testes': {'image':'true', 'group_name':'León Blanco', 'type': 'órgano/consumible', 'text': '<i>Un par de nueces pesadas.</i><br /><br />Probabilidad de obtención: 1/19.'},
'Shimmering Mane': {'image':'true', 'group_name':'León Blanco', 'type': 'piel', 'text': ' <i>Brilla a la luz de la linterna.</i><br /><br />Archiva esto para obtener 2 recursos básicos de piel.<br /><br />Probabilidad de obtención: 1/19.'},
'Sinew': {'image':'true', 'group_name':'León Blanco', 'type': 'órgano', 'text': '<i>Estos intestinos fibrosos son bastante útiles.</i><br /><br />Probabilidad de obtención: 2/19.'},
'White Fur': {'image':'true', 'group_name':'León Blanco', 'type': 'piel', 'text': '<i>Lujoso y suave al tacto.</i><br /><br />Probabilidad de obtención: 4/19.'},

'qqq': {'label': '???', 'group_name':'Básico', 'image': 'true', 'type': 'órgano/hueso/piel/consumible', 'text': '<i>No tienes idea de qué monstruo mordió esto.</i><br /><br />¡Se puede usar como hueso, órgano o piel!<br /><br />Probabilidad de obtención: 2/21.'},
'Broken Lantern': {'image': 'true', 'group_name':'Básico', 'type': 'desperdicio', 'text': '<i>Restos de una linterna apagada.</i><br /><br />Probabilidad de obtención: 2/21.'},
'Love Juice': {'image': 'true', 'group_name':'Básico', 'type': 'órgano/consumible', 'text': 'Durante la fase de asentamiento, puedes archivar esto para desencadenar '+event_img+'<b>Intimidad</b>. Los supervivientes nominados deben ser capaces de consumir.<br /><br />Probabilidad de obtención: 2/21.'},
'Monster Bone': {'image': 'true', 'group_name':'Básico', 'type': 'hueso', 'text': '<i>Un hueso adecuado para la creación.</i><br /><br />Probabilidad de obtención: 4/21.'},
'Monster Hide': {'image': 'true', 'group_name':'Básico', 'type': 'piel', 'text': '<i>La piel de una bestia.</i><br /><br />Probabilidad de obtención: 7/21.'},
'Monster Organ': {'image': 'true', 'group_name':'Básico', 'type': 'órgano/consumible', 'text': 'Si <b>consumes</b> esto, archiva esta carta. Tira 1d10:<br /><b style=\"color:#cc0;\">6+</b><div style="font-size:0.9em;display: inline;"> - contraes un parásito. Archiva todo el equipo consumible en tu cuadrícula ahora.</div><br /><br />Probabilidad de obtención: 3/21.'},
'Skull': {'image': 'true', 'group_name':'Básico', 'type': 'hueso', 'text': 'Cuando obtienes esto, un superviviente de tu elección gana +1 insanidad.<br /><br />Probabilidad de obtención: 1/21.'},

'1,000 Year Sunspot': {'type': 'hueso/órgano', 'group_name':'Sunstalker, Extraño',
                      'text': 'Cuando fabriques esto, nomina a un superviviente. Sufre la lesión grave <b>ciego</b> por trabajar con este recurso.'},
'3,000 Year Sunspot': {'type': 'hueso/órgano/desperdicio', 'group_name':'Sunstalker, Extraño',
                      'text': 'Cuando fabriques con esto, nombra a un superviviente y tira <b>1d10</b>:<br /><b style=\"color:#cc0;\">5+</b><div style="font-size:0.9em;display: inline;"> - les da un terrible dolor de cabeza y mueren.</div>'},
'Active Thyroid': {'type': 'órgano/consumible', 'group_name':'Gorm, Extraño',
                      'text': '<b>Consume</b>: archiva esto y tira <b>1d10</b>:<br /><b style=\"color:#cc0;\">1-6</b><div style="font-size:0.9em;display: inline;"> - tu corazón explota, matándote al instante.</div><br /><b style=\"color:#cc0;\">7+</b><div style="font-size:0.9em;display: inline;"> - ganas +1 velocidad permanente.</div>'},
'Black Lichen': {'type': 'hueso/órgano/piel/consumible/otro', 'group_name':'Extraño',
                'text': '<i>Maleable, punzante y atractivo.</i><br/><br/>Puedes <b>consumir</b> esto. Si lo haces, tus labios se vuelven grises, tu cabello blanquea y te vuelves infértil. Ganas +1 coraje, +1 comprensión y sufres la lesión de cintura grave <b>genitales destruidos</b>.'},
'Blistering Plasma Fruit': {'type': 'órgano/consumible', 'group_name':'Árbol Solitario, Extraño',
                'text': 'Puedes <b>consumir</b> y archivar esto para obtener la siguiente habilidad.<br /><br /><b>Sangre de Pesadilla</b>: Siempre que obtengas un token de sangrado, suma +1 a todos los lugares de impacto.'},
'Bugfish': {'type': 'pez/órgano', 'group_name':'Sunstalker, Extraño',
                'text': '<b>Consume</b>: Gana +2 supervivencia. <i>¡Hay algo en su vientre!</i> Gana 1 verme aleatorio y <b>consume</b>lo inmediatamente. Archiva esta carta.'},
'Canopic Jar': {'type': 'órgano/desperdicio', 'group_name':'Dios León, Extraño',
                'text': 'Cuando obtengas esto, quita 2 fichas de sangrado.<br /><br />Durante la fase de asentamiento, puedes archivar esto para '+event_img+'<b>Lectura de la Muerte</b>.'},
'Cocoon Membrane': {'type': 'órgano/otro', 'group_name':'Extraño',
                'text': '<i>Fibras de cobre delgadas impregnan esta sustancia gelatinosa. Las linternas son repelidas por las fibras de cobre, doblando su luz para evitarlas.</i>'},
'Crimson Vial': {'type': 'hierro/consumible', 'group_name':'Cazador de Hombres, Extraño',
                'text': 'Puedes <b>consumir</b> y archivar esto para eliminar todos los tokens de sangrado y cualquier lesión grave de tu elección.'},
'Crystal Sword Mold': {'type': 'desperdicio/hierro', 'group_name':'Hombre Esbelto, Extraño',
                'text': '<i>Este extraño cristal refracta la luz, concentrándola en una cámara natural con forma de espada.</i>'},
'Dark Water': {'type': 'otro', 'group_name':'Hombre Esbelto, Extraño',
                'text': 'Puedes <b>consumir</b> y archivar esto para eliminar todos tus trastornos, luego ganar un trastorno aleatorio.'},
'Drifting Dream Fruit': {'type': 'consumible', 'group_name':'Árbol Solitario, Extraño',
                'text': 'Puedes <b>consumir</b> y archivar esto para seleccionar un Sueño en el '+event_img+'<b>Nacimiento de un Salvador</b> y ganar todas las habilidades asociadas.'},
'Elder Cat Teeth': {'type': 'hueso', 'group_name':'León Blanco, Extraño',
                'text': '<i>Tan afilados como extraños</i>'},
'Fresh Acanthus': {'type': 'hierba', 'group_name':'Extraño',
                'text': 'Archiva esto para curar completamente 1 ubicación de impacto, incluidos los niveles de lesiones y los puntos de armadura.'},
'Gormite': {'type': 'desperdicio/hierro', 'group_name':'Gorm, Extraño',
                'text': '<i>Lo más resistente conocido por el hombre.</i>'},
'Hagfish': {'type': 'pez/hueso/piel', 'group_name':'Sunstalker, Extraño',
                'text': '<b>Consume</b>: Tu cabello se vuelve gris y ganas +1 XP de Caza. Archiva la carta.'},
'Iron': {'type': 'desperdicio/hierro', 'group_name':'Extraño',
                'text': '<i>Más duro que el hueso.</i>'},
'Jagged Marrow Fruit': {'type': 'hueso/desperdicio/consumible', 'group_name':'Árbol Solitario, Extraño',
                'text': 'Puedes <b>consumir</b> y archivar esto para obtener la siguiente habilidad.<br /><br /><b>Estímulos de Pesadilla</b>: Una vez por enfrentamiento, puedes gastar toda tu supervivencia (al menos 1) para perder todos tus tokens de +1 fuerza y ganar la misma cantidad de tokens de +1 suerte.'},
'Jowls': {'type': 'pez/hierro', 'group_name':'Sunstalker, Extraño',
                'text': 'Cuando obtengas Jowls, ¡te arranca la nariz! Si no tienes nariz, mueres.<br /><br />Si tienes <b>Jowls</b>, <b>Hagfish</b> y <b>Bugfish</b>, ¡estás inspirado! Puedes archivar los 3 para obtener la innovación <b>Mesa de Fileteado</b>.'},
'Lantern Tube': {'type': 'órgano/desperdicio', 'group_name':'Extraño',
                'text': '<i>Un tubo carnoso con revestimiento muscular.</i><br /><br />Cuando obtienes esto, tira <b>1d10</b>:<br /><b style=\"color:#cc0;\">6+</b><div style="font-size:0.9em;display: inline;"> - ¡encuentras algo atascado adentro! Agrega 1 recurso básico <b>Linterna Rota</b> al depósito del asentamiento.</div>'},
'Leather': {'type': 'piel/cuero', 'group_name':'Extraño',
                'text': '<i>Nunca pasa de moda</i>'},
'Legendary Horns': {'type': 'hueso/desperdicio', 'group_name':'Antílope Gritón, Extraño',
                'text': '<i>Sostenerlos te llena de poder.</i>'},
'Lonely Fruit': {'type': 'consumible', 'group_name':'Árbol Solitario, Extraño',
                'text': 'Durante la fase de asentamiento, puedes <b>consumir</b> y archivar esto para '+event_img+'<b>Dama Solitaria</b>.'},
'Old Blue Box': {'type': 'desperdicio', 'group_name':'Dios León, Extraño',
                'text': 'Durante la fase de asentamiento, puedes archivar esto para '+event_img+'<b>Lectura de la Muerte</b>.'},
'Perfect Crucible': {'type': 'hierro', 'group_name':'Extraño',
                'text': 'Cuando fabriques con el Perfect Crucible, una antigua bacteria se libera en el aire. Sufre -1d10 en población y archiva esta carta.'},
'Phoenix Crest': {'type': 'órgano', 'group_name':'Fénix, Extraño',
                'text': '<i>Firme y flexible.</i>'},
'Pituitary Gland': {'type': 'órgano', 'group_name':'Rey Dragón, Extraño',
                'text': '<b>Consume</b>: Archiva esto y tira <b>1d10</b>:<br /><b style=\"color:#cc0;\">1-3</b><div style="font-size:0.9em;display: inline;"> - creces a un tamaño gigante y mueres.</div><br /><b style=\"color:#cc0;\">4+</b><div style="font-size:0.9em;display: inline;"> - ganas +1 fuerza permanente.</div>'},
'Porous Flesh Fruit': {'type': 'piel/consumible', 'group_name':'Árbol Solitario, Extraño',
                'text': 'Puedes consumir y archivar esto para obtener la siguiente habilidad.<br /><br /><b>Membrana de Pesadilla</b>: Puedes gastar {image@images/icons/movement} y {image@images/icons/activation} para intercambiar cualquier token tuyo por un token de +1 fuerza.'},
'Preserved Caustic Dung': {'type': 'órgano/consumible/desecho', 'group_name':'Caballero del Escarabajo Pelotero, Extraño',
                'text': '<i>Las culturas vivas en esta exótica mezcla de excremento maduro se han preservado en una delicada cubierta de gel hermética.</i>'},
'Pure Bulb': {'type': 'órgano', 'group_name':'Gorm, Extraño',
                'text': '<i>No mires fijamente esto.</i>'},
'Radiant Heart': {'type': 'órgano', 'group_name':'Rey Dragón, Extraño',
                'text': 'Cuando obtienes este recurso, tira <b>1d10</b>:<br /><b style=\"color:#cc0;\">3+</b><div style="font-size:0.9em;display: inline;"> - te incendias y mueres.</div>'},
'Red Vial': {'type': 'consumible', 'group_name':'Cazador de Hombres, Extraño',
                'text': 'Puedes <b>consumir</b> y archivar esto para eliminar 2 tokens de sangrado y ganar +1 supervivencia.'},
'Salt': {'type': 'sal', 'group_name':'Sunstalker, Extraño',
                'text': '<i>Cuando se expone a la luz de la linterna, se evapora, formando una costra.</i><br /><br />Puedes agregar esto a cualquier receta de cocina para ganar +1 fuerza permanente además de los beneficios enumerados en la receta.'},
'Scell': {'type': 'órgano/consumible', 'group_name':'Caballero del Escarabajo Pelotero, Extraño',
                'text': '<i>A medida que el monstruo envejece, este material pegajoso y corrosivo se acumula entre las finas capas de sus conchas de escarabajo. Descompone el producto fecal, evitando que las articulaciones del caballero se bloqueen.</i><br /><br />Durante la <b>Cosecha Negra</b>, un Restaurador puede aprovechar al máximo un Scell, usándolo para casi perfeccionar el último paso del proceso de calcificación.'},
'Sarcophagus': {'type': 'hierro', 'group_name':'Dios León, Extraño',
                'text': '-2 de movimiento mientras tengas esto.<br /><br />Durante la fase de asentamiento, puedes archivar esto para '+event_img+'<b>Lectura de la Muerte</b>.'},
'Second Heart': {'type': 'órgano/hueso', 'group_name':'Antílope Gritón, Extraño',
                'text': '<i>Todavía intenta morderte.</i>'},
'Shining Liver': {'type': 'órgano', 'group_name':'Rey Dragón, Extraño',
                'text': '<i>Cuando se expone a la luz, filtra el calor y se vuelve más oscuro.</i>'},
'Silken Nervous System': {'type': 'órgano', 'group_name':'Spidicules, Extraño',
                'text': '<i>Se separa en diminutos hilos dorados.</i>'},
'Silver Urn': {'type': 'hueso/desperdicio', 'group_name':'Dios León, Extraño',
                'text': 'Durante la fase de asentamiento, puedes archivar esto para '+event_img+'<b>Lectura de la Muerte</b>.'},
'Stomach Lining': {'type': 'órgano', 'group_name':'Gorm, Extraño',
                'text': '<i>Se expande y contrae constantemente.</i>'},
'Sunstones': {'type': 'hueso', 'group_name':'Sunstalker, Extraño',
                'text': '<i>Pequeños y cálidos.</i>'},
'Triptych': {'type': 'piel/desperdicio', 'group_name':'Dios León, Extraño',
                'text': 'Cuando obtienes esto, obtienes +3 de insanidad.<br /><br />Durante la fase de asentamiento, puedes archivar esto para '+event_img+'<b>Lectura de la Muerte</b>.'},
'Web Silk': {'type': 'seda', 'group_name':'Spidicules, Extraño',
                'text': '<i>Imposible de rasgar.</i>'},

'Metal Face': {'type':'desperdicio', 'group_name':'Extraño', 'text': '<i>Una fuerza magnética emana del metal.</i><br /><br />Durante la fase de asentamiento, puedes archivar 3 recursos extraños de <b>Metal Face</b> para agregar 1 equipo raro <b>Storm Helmet</b> al depósito del asentamiento.'},

'Hooked Claw': {'type':'hueso', 'group_name':'Gigalión Blanco, Extraño', 'text': '<i>Manchada con motas de antigua sangre seca y fragmentos de pelo osificado.</i>'},

'Allisons Legacy': {'label':'Legado de Allison', 'type': 'piel/other', 'group_name':'Extraño',
                'text': '<i>Un relato personal que detalla el trabajo desinteresado de Allison, la Caballera del Crepúsculo.</i><br/><br/>Durante la fase de asentamiento, un sobreviviente puede gastar {image@images/icons/endeavors} para leer el libro. Los secretos contenidos son tan profundos que ganan el trastorno <b>Miedo a la Oscuridad</b>.<br/><br/>Si se lee el libro, todos los <b>Aprendices</b> ganan +1 fuerza permanente. Si un sobreviviente con proficiencia en la Espada del Crepúsculo tiene 8 puntos de experiencia con armas, ganan <b>Maestría en la Espada del Crepúsculo</b>.<br/><br/>Archiva esta carta.'},
'Copper': {'type': 'desperdicio', 'group_name':'Extraño',
                'text': '<i>Más raro que el hierro.</i>'},
'Lantern Nerve Bundle': {'type': 'órgano/consumible', 'group_name':'Extraño',
                'text': 'Archiva esto para realizar una demostración electrizante de fuerza.<br/><br/><b style=\"color:#cc0;\">1-3</b><div style="font-size:0.9em;display: inline;"> - La sustancia se endurece incómodamente. Sufre -1 movimiento permanente.</div><br /><b style=\"color:#cc0;\">4-8</b><div style="font-size:0.9em;display: inline;"> - Se endurece en una concha resistente. Cuando <b>te marches</b>, agrega +3 de armadura a la ubicación del cuerpo.</div><br /><b style=\"color:#cc0;\">9+</b><div style="font-size:0.9em;display: inline;"> - Gana +1 evasión permanente.</div>'},
'Skeletal Shards': {'type': 'hueso', 'group_name':'Extraño',
                'text': '<i>La médula azul pulsante parece suave y maleable antes de endurecerse.</i><br/><br/>Los Skeletal Shards pueden sustituirse en cualquier receta que requiera un hueso específico de monstruo.'},
'Watcher Jelly': {'type': 'órgano/consumible', 'group_name':'Extraño',
                'text': '<b>Aplicar</b>: Archiva esto y tira <b>1d10</b>.<br/><br/><b style=\"color:#cc0;\">1-3</b><div style="font-size:0.9em;display: inline;"> - La sustancia se endurece incómodamente. Sufre -1 movimiento permanente.</div><br /><b style=\"color:#cc0;\">4-8</b><div style="font-size:0.9em;display: inline;"> - Se endurece en una concha resistente. Cuando <b>te marches</b>, agrega +3 de armadura a la ubicación del cuerpo.</div><br /><b style=\"color:#cc0;\">9+</b><div style="font-size:0.9em;display: inline;"> - Gana +1 evasión permanente.</div>'},
'Whispering Whetstone': {'type': 'desperdicio/other', 'group_name':'Extraño',
                'text': '<i>Susurra solo para ti.</i><br/><br/>{image@images/icons/endeavors}: Archiva esto para afilar una de las siguientes armas en el depósito del asentamiento: hacha, espada, daga, guadaña, katana o katar. Dura hasta el final del próximo enfrentamiento. Después de archivarlo, obtén 1 recurso extraño de <b>hierro</b>.'},



'Destroyed Barb': {'type': 'hueso', 'group_name':'Caballero Vagabundo, Extraño', 'text': '<i>Simplemente manejarlo hace que brote sangre.</i>'},
'Neurotoxin': {'type': 'órgano', 'group_name':'Caballero Vagabundo, Extraño', 'text': '<i>Causa la muerte instantánea de sobrevivientes y otras alimañas.</i>'},

'Bile duct': {'type': 'hueso/pellejo/órgano', 'group_name':'Caballero Vagabundo', 'text': '<i>Ignora el hecho de que no tiene estómago.</i><br /><br />Probabilidad de caída: 2/15.'},
'Exquisite Fabric': {'type': 'pellejo/seda', 'group_name':'Caballero Vagabundo', 'text': '<i>Una mirada y te atrae por completo.</i><br /><br />Probabilidad de caída: 1/15.'},
'Fleshy Armor': {'type': 'pellejo', 'group_name':'Caballero Vagabundo', 'text': '<i>Sorprendentemente resistente, tiene sabor a pez lobo.</i><br /><br />Probabilidad de caída: 4/15.'},
'Petrified Plate': {'type': 'hueso/desperdicio', 'group_name':'Caballero Vagabundo', 'text': '<i>Miles de años de calor en una sola placa.</i><br /><br />Probabilidad de caída: 2/15.'},
'Silken Skin': {'type': 'órgano/seda', 'group_name':'Caballero Vagabundo', 'text': '<i>Parece fabulosa bajo cualquier iluminación.</i><br /><br />Probabilidad de caída: 2/15.'},
'Stinging Tendrils': {'type': 'órgano', 'group_name':'Caballero Vagabundo', 'text': '<i>Difícil de agarrar sin guantes.</i><br /><br />Probabilidad de caída: 4/15.'},

}

module.exports = {
 texts,
}
