const gear = {
 'Acid Tooth Dagger':{
   'location': 'gormery'
   'keywords': ''
   'affinities': 'rwrw'
 },
 'Adventure Sword',
 'Almanac',
 'Amber Edge',
 'Amber Poleaxe',
 'Ancient Lion Claws',
 'Antelope Mask',
 'Apostle Crown',
 'Arc Bow',
 'Armor Spikes',
 'Bandages',
 'Beacon Shield',
 'Beast Knuckle',
 'Bird Bread',
 'Black Sword',
 'Blast Shield',
 'Blast Sword',
 'Blood Paint',
 'Blood Sheath',
 'Bloodskin',
 'Bloom Sphere',
 'Blue Charm',
 'Blue Lantern',
 'Blue Power Core',
 'Blue Ring',
 'Bone Axe',
 'Bone Blade',
 'Bone Club',
 'Bone Dagger',
 'Bone Darts',
 'Bone Earrings',
 'Bone Pickaxe',
 'Bone Sickle',
 'Bone Witch Mehndi',
 'Boss Mehndi',
 'Brain Mint',
 'Bug Trap',
 'Butcher Cleaver',
 'Butchers Blood',
 'Calcified Digging Claw',
 'Calcified Greaves',
 'Calcified Juggernaut Blade',
 'Calcified Shoulder Pads',
 'Calcified Zanbato',
 'Cat Eye Circlet',
 'Cat Fang Knife',
 'Cat Gut Bow',
 'Celestial Spear',
 'Century Greaves',
 'Century Shoulder Pads',
 'Claw Head Arrow',
 'Cloth',
 'Cloth Leggings',
 'Counterweighted Axe',
 'Crest Crown',
 'Cycloid Scale Hood',
 'Cycloid Scale Jacket',
 'Cycloid Scale Shoes',
 'Cycloid Scale Skirt',
 'Cycloid Scale Sleeves',
 'DBK Errant Badge',
 'Dark Water Vial',
 'Death Mask',
 'Death Mehndi',
 'Deathpact',
 'Denticle Axe',
 'Digging Claw',
 'Dormant Twilight Cloak',
 'Dragon Belt',
 'Dragon Bite Bolt',
 'Dragon Boots',
 'Dragon Chakram',
 'Dragon Gloves',
 'Dragon Mantle',
 'Dragon Slayer',
 'Dragon Vestments',
 'Dragonskull Helm',
 'Dried Acantus',
 'Elder Earrings',
 'Eye Patch',
 'Feather Mantle',
 'Feather Shield',
 'Fecal Salve',
 'Fetorsaurus',
 'Final Lantern',
 'Finger of God',
 'First Aid Kit',
 'Flower Knight Badge',
 'Flower Knight Helm',
 'Forsaker Mask',
 'Founding Stone',
 'Frenzy Drink',
 'Gaxe',
 'Gloom Bracelets',
 'Gloom Cream',
 'Gloom Hammer',
 'Gloom Katana',
 'Gloom Mehndi',
 'Gloom Sheath',
 'Gloom-Coated Arrow',
 'Glyph of Solitude',
 'God Mask',
 'Gods String',
 'Golden Plate',
 'Gorment Boots',
 'Gorment Mask',
 'Gorment Sleeves',
 'Gorment Suit',
 'Gorn',
 'Greater Gaxe',
 'Green Boots',
 'Green Charm',
 'Green Faulds',
 'Green Gloves',
 'Green Helm',
 'Green Plate',
 'Green Ring',
 'Grinning Visage',
 'Griswaldo',
 'Hard Breastplate',
 'Hazmat Shield',
 'Healing Potion',
 'Hidden Crimson Jewel',
 'Hideous Disguise',
 'Hollow Sword',
 'Hollowpoint Arrow',
 'Hooded Scrap Katar',
 'Hours Ring',
 'Hunter Whip',
 'Hunters Heart',
 'Husk of Destiny',
 'Ink Blood Bow',
 'Ink Sword',
 'King Spear',
 'Knuckle Shield',
 'Lance of Longinus',
 'Lantern Cuirass',
 'Lantern Dagger',
 'Lantern Gauntlets',
 'Lantern Greaves',
 'Lantern Halberd',
 'Lantern Helm',
 'Lantern Mail',
 'Lantern Mehndi',
 'Lantern Sword',
 'Leather Boots',
 'Leather Bracers',
 'Leather Cuirass',
 'Leather Mask',
 'Leather Skirt',
 'Life Elixir',
 'Lion Beast Katar',
 'Lion God Statue',
 'Lion Headdress',
 'Lion Knight Badge',
 'Lion Knights Left Claw',
 'Lion Knights Right Claw',
 'Lion Skin Cloak',
 'Lucky charm',
 'Man Mask',
 'Manhunters Hat',
 'Monster Grease',
 'Monster Tooth Necklace',
 'Muramasa',
 'Musk Bomb',
 'Necromancers Eye',
 'Newborn',
 'Nuclear Knife',
 'Nuclear Scythe',
 'Oxidized Beacon Shield',
 'Oxidized Lantern Dagger',
 'Oxidized Lantern Glaive',
 'Oxidized Lantern Helm',
 'Oxidized Lantern Sword',
 'Oxidized Ring Whip',
 'Perfect Slayer',
 'Phoenix Faulds',
 'Phoenix Gauntlet',
 'Phoenix Greaves',
 'Phoenix Helm',
 'Phoenix Mask',
 'Phoenix Plackart',
 'Power Potion',
 'Prism Mace',
 'Pulse Lantern',
 'Quiver and Sun String',
 'Rainbow Katana',
 'Rainbow Wing Belt',
 'Raptor-Worm Collar',
 'Rawhide Boots',
 'Rawhide Drum',
 'Rawhide Gloves',
 'Rawhide Headband',
 'Rawhide Pants',
 'Rawhide Vest',
 'Rawhide Whip',
 'Red Charm',
 'Red Power Core',
 'Red Ring',
 'Regal Edge',
 'Regal Faulds',
 'Regal Gauntlet',
 'Regal Greaves',
 'Regal Helm',
 'Regal Plackart',
 'Regenerating Blade',
 'Regeneration Suit',
 'Replica Flower Sword',
 'Reverberating Lantern',
 'Rib Blade',
 'Ring Whip',
 'Riot Mace',
 'Round Leather Shield',
 'Rubber Bone Harness',
 'Satchel',
 'Scarab Circlet',
 'Scavenger Kit',
 'Scrap Dagger',
 'Scrap Shield',
 'Scrap Sword',
 'Screaming Bracers',
 'Screaming Coat',
 'Screaming Horns',
 'Screaming Leg Warmers',
 'Screaming Skirt',
 'Seasoned Monster Meat',
 'Shadow Saliva Shawl',
 'Shielded Quiver',
 'Silk Body Suit',
 'Silk Bomb',
 'Silk Boots',
 'Silk Robes',
 'Silk Sash',
 'Silk Turban',
 'Silk Whip',
 'Silk Wraps',
 'Skleaver',
 'Skull Helm',
 'Skullcap Hammer',
 'Sky Harpoon',
 'Sleeping Virus Flower',
 'Slender Ovule',
 'Sonic Tomahawk',
 'Speaker Cult Knife',
 'Speed Powder',
 'Steadfast Potion',
 'Steel Shield',
 'Steel Sword',
 'Stone Noses',
 'Sun Lure and Hook',
 'Sun Vestments',
 'Sunring Bow',
 'Sunshark Arrows',
 'Sunshark Bow',
 'Sunspot Dart',
 'Sunspot Lantern',
 'Survivors Lantern',
 'Sword of Silence',
 'Tabard',
 'Talon Knife',
 'The Beetle Bomb',
 'The Weaver',
 'Throwing Knife',
 'Thunder Maul',
 'Tool Belt',
 'Trash Crown',
 'Twilight Sword',
 'Vespertine Arrow',
 'Vespertine Bow',
 'Vespertine Cello',
 'Vespertine Foil',
 'Whisker Harp',
 'Whistling Mace',
 'White Dragon Gauntlets',
 'White Lion Boots',
 'White Lion Coat',
 'White Lion Gauntlet',
 'White Lion Helm',
 'White Lion Mask',
 'White Lion Skirt',
 'Wisdom Potion',
 'Zanbato'
}
