const quary_events = [
  'dragon king 1.jpg',
  'dragon king 2.jpg',
  'dragon king 3.jpg',
  'dragon king 4.jpg',
  'dragon king 5.jpg',
  'dragon king 6.jpg',
  'dragon king 7.jpg',
  'dragon king 8.jpg',
  'dung beetle knight 1.jpg',
  'dung beetle knight 2.jpg',
  'dung beetle knight 3.jpg',
  'dung beetle knight 4.jpg',
  'dung beetle knight 5.jpg',
  'dung beetle knight 6.jpg',
  'dung beetle knight 7.jpg',
  'gorm 1.jpg',
  'gorm 2.jpg',
  'gorm 3.jpg',
  'gorm 4.jpg',
  'gorm 5.jpg',
  'gorm 6.jpg',
  'gorm 7.jpg',
  'lion god 1.jpg',
  'lion god 2.jpg',
  'lion god 3.jpg',
  'lion god 4.jpg',
  'lion god 5.jpg',
  'lion god 6.jpg',
  'lion god 7.jpg',
  'lion god 8.jpg',
  'phoenix 1.jpg',
  'phoenix 2.jpg',
  'phoenix 3.jpg',
  'phoenix 4.jpg',
  'phoenix 5.jpg',
  'phoenix 6.jpg',
  'phoenix 7.jpg',
  'phoenix 8.jpg',
  'phoenix 9.jpg',
  'screaming antelope 1.jpg',
  'screaming antelope 2.jpg',
  'screaming antelope 3.jpg',
  'screaming antelope 4.jpg',
  'screaming antelope 5.jpg',
  'screaming antelope 6.jpg',
  'screaming antelope 7.jpg',
  'screaming antelope 8.jpg',
  'screaming antelope 9.jpg',
  'sunstalker 1.jpg',
  'sunstalker 2.jpg',
  'sunstalker 3.jpg',
  'sunstalker 4.jpg',
  'sunstalker 5.jpg',
  'sunstalker 6.jpg',
  'sunstalker 7.jpg',
  'sunstalker 8.jpg',
  'white lion 1.jpg',
  'white lion 2.jpg',
  'white lion 3.jpg',
  'white lion 4.jpg',
  'white lion 5.jpg',
  'white lion 6.jpg',
  'white lion 7.jpg',
  'white lion 8.jpg',
  'gigalion 1.jpg',
  'gigalion 2.jpg',
  'gigalion 3.jpg',
  'gigalion 4.jpg',
  'gigalion 5.jpg',
  'gigalion 6.jpg',
  'gigalion 7.jpg',
  'gigalion 8.jpg',
  'flower knight 1.jpg',
  'flower knight 2.jpg',
  'flower knight 3.jpg',
  'flower knight 4.jpg',
  'flower knight 5.jpg',
  'flower knight 6.jpg',
  'flower knight 7.jpg',
  'flower knight 8.jpg',
  'flower knight 9.jpg',
  'spidicules 1.jpg',
  'spidicules 2.jpg',
  'spidicules 3.jpg',
  'spidicules 4.jpg',
  'spidicules 5.jpg',
  'spidicules 6.jpg',
  'spidicules 7.jpg',
  'spidicules 8.jpg',
  'spidicules 9.jpg',
  'drifter knight 1.jpg',
  'drifter knight 2.jpg',
  'drifter knight 3.jpg',
  'drifter knight 4.jpg',
  'drifter knight 5.jpg',
  'drifter knight 6.jpg',
  'drifter knight 7.jpg',
  'drifter knight 8.jpg',
  'drifter knight 9.jpg',
]

module.exports = {
  quary_events,
}
