const texts = {
  'gorm': {
    'board':'xmmrrmxrrmmr',
    'monster_position': [5, 8, 12],
    'monster_icon':'images/hunt/gorm.png',
    'monster_icon_width':8,
    'monster_icon_height':40,
    'label': 'Gorm',
    'showdown': 'showdown gorm',
  },
  'white lion': {
    'board':'xmmrrmxrmmrr',
    'monster_position': [5, 8, 12],
    'monster_icon':'images/hunt/white_lion.png',
    'monster_icon_width':8,
    'monster_icon_height':41,
    'label': 'White Lion',
    'showdown': 'showdown white lion',
  },
  'gigalion': {
    'board':'xrrrrmxmrmmr',
    'monster_position': [0, 9, 12],
    'monster_icon':'images/hunt/gigalion.png',
    'monster_icon_width':8,
    'monster_icon_height':41,
    'label': 'White Giga Lion',
    'showdown': 'showdown gigalion',
  },
  'screaming antelope': {
    'board':'xmrmrrxmrmrr',
    'monster_position': [5, 9, 11],
    'monster_icon':'images/hunt/screaming_antelope.png',
    'monster_icon_width':7,
    'monster_icon_height':38,
    'label': 'Screaming Antelope',
    'showdown': 'showdown screaming antelope',
  },
  'flower knight': {
    'board':'xrrrrrxmmmmm',
    'monster_position': [9, 10, 11],
    'monster_icon':'images/hunt/flower knight.png',
    'monster_icon_width':9,
    'monster_icon_height':38.8,
    'label': 'Flower Knight',
    'showdown': 'showdown flower knight',
  },
  'spidicules': {
    'board':'xmmrrmxrmmrr',
    'monster_position': [5, 8, 11],
    'monster_icon':'images/hunt/spidicules.png',
    'monster_icon_width':9,
    'monster_icon_height':41,
    'label': 'Spidicules',
    'showdown': 'showdown spidicules',
  },
  'drifter knight': {
    'board':'xmrrmrxmrmrr',
    'monster_position': [6, 9, 11],
    'monster_icon':'images/hunt/drifter knight.png',
    'monster_icon_width':7,
    'monster_icon_height':38,
    'label': 'Drifter Knight',
    'showdown': 'showdown drifter knight',
  },
  'phoenix': {
    'board':'xrmrmrxmrmrr',
    'monster_position': [6, 9, 12],
    'monster_icon':'images/hunt/phoenix.png',
    'monster_icon_width':8,
    'monster_icon_height':42,
    'label': 'Phoenix',
    'showdown': 'showdown phoenix',
  },
  'dung beetle knight': {
    'board':'xrmmrrxmrrmr',
    'monster_position': [6, 9, 12],
    'monster_icon':'images/hunt/dung_beetle_knight.png',
    'monster_icon_width':8,
    'monster_icon_height':40,
    'label': 'Dung Beetle Knight',
    'showdown': 'showdown dung beetle knight',
  },
  'sunstalker': {
    'board':'xrmmrrxmrrmr',
    'monster_position': [5, 9, 12],
    'monster_icon':'images/hunt/sunstalker.png',
    'monster_icon_width':8,
    'monster_icon_height':42,
    'label': 'Sunstalker',
    'showdown': 'showdown sunstalker',
  },
  'dragon king': {
    'board':'xmrmmrxmrrmr',
    'monster_position': [6, 9, 12],
    'monster_icon':'images/hunt/dragon_king.png',
    'monster_icon_width':8,
    'monster_icon_height':42,
    'label': 'Dragon King',
    'showdown': 'showdown dragon king',
  },
  'lion god': {
    'board':'xrmrmrxrmrmr',
    'monster_position': [8, 10, 12],
    'monster_icon':'images/hunt/lion_god.png',
    'monster_icon_width':9,
    'monster_icon_height':39,
    'label': 'Lion God',
    'showdown': 'showdown lion god',
  },
}

module.exports = {
 texts,
}
