const texts = {
'Cabled Vein (Dragon King)': {'label':'', 'type': 'organ', 'text': 'A dense bundle of bloody tubes.<br\><br\><i>Drop chance: 2/21.</i>'},
'Dragon Iron (Dragon King)': {'type': 'iron', 'text': 'It feels heavy, but when dropped, falls as slowly as a feather.<br\><br\><i>Drop chance: 1/21.</i>'},
'Hardened Ribs (Dragon King)': {'type': 'bone', 'text': 'Strong, flexible, and hollow.<br\><br\><i>Drop chance: 1/21.</i>'},
'Horn Fragment (Dragon King)': {'type': 'bone', 'text': 'Nearby speech causes them to resonate.<br\><br\><i>Drop chance: 4/21.</i>'},
'Husk (Dragon King)': {'type': 'hide', 'text': 'A decaying layer of former skin.<br\><br\><i>Drop chance: 3/21.</i>'},
'King\'s Claws (Dragon King)': {'type': 'bone', 'text': 'Disturbingly warm, and sharp enough to draw blood with a touch.<br\><br\><i>Drop chance: 4/21.</i>'},
'King\'s Tongue (Dragon King)': {'type': 'hide', 'text': 'Smooth, dry, and sharp.<br\><br\><i>Drop chance: 1/21.</i>'},
'Radioactive Drug (Dragon King)': {'type': 'organ/scrap', 'text': 'Gives off smoke with an acrid odor.<br\><br\><i>Drop chance: 2/21.</i>'},
'Veined Wing (Dragon King)': {'type': 'hide', 'text': 'Blood drips from it at a constant rate.<br\><br\><i>Drop chance: 3/21.</i>'},

'Beetle Horn (Dung Beetle Knight)': {'type': 'bone', 'text': '<i>Drop chance: 1/11.</i>'},
'Century Fingernails (Dung Beetle Knight)': {'type': 'bone', 'text': 'These nails are never clipped. Instead, they are folded and hammered hundreds of times into an impossibly fine edge.<br\><br\><i>Drop chance: 2/11.</i>'},
'Century Shell (Dung Beetle Knight)': {'type': 'hide/iron', 'text': 'This ancient and mineral-rich armor plate is covered with razor wind scratches. You may spend this as if it were a Scarab Shell resource.<br\><br\><i>Drop chance: 1/11.</i>'},
'Compound Eye (Dung Beetle Knight)': {'type': 'organ/consumable', 'text': 'A cluster of differently colored eyes, each filled with a creamy, tangy syrup. If you have 3+ courage, you may consume and archive this to gain +3d10 insanity.<br\><br\><i>Drop chance: 1/11.</i>'},
'Elytra (Dung Beetle Knight)': {'type': 'bone/hide/organ', 'text': 'The ribbed underside of these large shells makes an ideal surface to grind weapons. A survivor may archive this to give all of their attacks in the next showdown Sharp.<br\><br\><i>Drop chance: 1/11.</i>'},
'Scarab Shell (Dung Beetle Knight)': {'type': 'hide', 'text': 'Cool and oily to the touch. Lantern light reveals a brilliant band of color dancing on its surface.<br\><br\><i>Drop chance: 3/11.</i>'},
'Scarab Wing (Dung Beetle Knight)': {'type': 'organ', 'text': 'When soaked in water, these vein-filled wings gain some elasticity.<br\><br\><i>Drop chance: 1/11.</i>'},
'Underplate Fungus (Dung Beetle Knight)': {'type': 'herb/hide/consumable', 'text': 'A corkscrew-shaped fungus that grows in the empty channels between the Dung Beetle Knight\'s armor plating.<br\><br\><i>Drop chance: 1/11.</i>'},

'Lantern Bloom (Flower Knight)': {'type': 'flower/hide', 'text': 'Perishable.<br/>You may consume and archive this during the showdown to gain +3 luck tokens, -1 permanent luck, and the Flower Addiction disorder.<br\>vDrop chance: 3/14.</i>'},
'Lantern Bud (Flower Knight)': {'type': 'flower/scrap', 'text': 'Perishable.<br/>You may consume and archive this during the settlement phase to gain +3 [Endeavor], skip the next hunt, and gain the Flower Addiction disorder.<br\><br\><i>Drop chance: 1/14.</i>'},
'Osseous Bloom (Flower Knight)': {'type': 'flower/bone', 'text': 'Perishable.<br/>You may consume and archive this during the showdown to remove all your bleeding and negative attribute tokens and gain the Flower Addiction disorder.<br\><br\><i>Drop chance: 5/14.</i>'},
'Sighing Bloom (Flower Knight)': {'type': 'flower/organ', 'text': 'Perishable.<br/>You may consume and archive this during the showdown to gain 3 survival, 3 insanity, and the Flower Addiction disorder.<br\><br\><i>Drop chance: 3/14.</i>'},
'Warbling Bloom (Flower Knight)': {'type': 'flower/hide', 'text': 'Perishable.<br/>You may plant this during the settlement phase to archive it and gain +1 population. The survivor is born with the Flower Addiction disorder and a face just like the Warbling Bloom\'s.<br\><br\><i>Drop chance: 2/14.</i>'},

'Acid Gland (Gorm)': {'type': 'organ', 'text': 'Melts skin.<br\><br\><i>Drop chance: 1/21.</i>'},
'Dense Bone (Gorm)': {'type': 'bone', 'text': 'Sturdy.<br\><br\><i>Drop chance: 2/21.</i>'},
'Gorm Brain (Gorm)': {'type': 'organ', 'text': 'Shockingly small.<br\><br\><i>Drop chance: 1/21.</i>'},
'Handed Skull (Gorm)': {'type': 'bone', 'text': 'Incomparably dense.<br\><br\><i>Drop chance: 1/21.</i>'},
'Jiggling Lard (Gorm)': {'type': 'organ/hide', 'text': 'Thick, quivering mass.<br\><br\><i>Drop chance: 2/21.</i>'},
'Mammoth Hand (Gorm)': {'type': 'bone/hide/organ', 'text': 'An enormous, leathery glove.<br\><br\><i>Drop chance: 2/21.</i>'},
'Meaty Rib (Gorm)': {'type': 'bone/organ', 'text': 'Useful and delicious.<br\><br\><i>Drop chance: 2/21.</i>'},
'Milky Eye (Gorm)': {'type': 'organ', 'text': 'When this resource is gained, select a survivor to gain +3 insanity.<br\><br\><i>Drop chance: 1/21.</i>'},
'Stout Heart (Gorm)': {'type': 'organ', 'text': 'A titanic pump.<br\><br\><i>Drop chance: 2/21.</i>'},
'Stout Hide (Gorm)': {'type': 'hide', 'text': 'Touch, wrinkly skin.<br\><br\><i>Drop chance: 4/21.</i>'},
'Stout Kidney (Gorm)': {'type': 'organ', 'text': 'Consume: archive this and roll 1d10. On a result of 6+, gain 10 survival. Otherwise reduce your survival to 0.<br\><br\><i>Drop chance: 2/21.</i>'},
'Stout Vertebrae (Gorm)': {'type': 'bone', 'text': 'Hefty and intricately joined.<br\><br\><i>Drop chance: 1/21.</i>'},

'Bird Beak (Phoenix)': {'type': 'bone', 'text': 'Surprisingly toothy.<br\><br\><i>Drop chance: 1/24.</i>'},
'Black Skull (Phoenix)': {'type': 'iron/skull/bone', 'text': 'Aged to perfection.<br\><br\><i>Drop chance: 1/24.</i>'},
'Hollow Wing Bones (Phoenix)': {'type': 'bone', 'text': 'Delicate and finely balanced.<br\><br\><i>Drop chance: 3/24.</i>'},
'Muculent Droppings (Phoenix)': {'type': 'organ', 'text': 'Delicately scented, papery husk.<br\><br\><i>Drop chance: 3/24.</i>'},
'Phoenix Eye (Phoenix)': {'type': 'organ/scrap', 'text': 'Filled with a thick, metallic liquid.<br\><br\><i>Drop chance: 1/24.</i>'},
'Phoenix Finger (Phoenix)': {'type': 'bone', 'text': 'When you gain this, a survivor of your choice gains +3 insanity.<br\><br\><i>Drop chance: 2/24.</i>'},
'Phoenix Whisker (Phoenix)': {'type': 'hide', 'text': 'Silky, yet robust.<br\><br\><i>Drop chance: 1/24.</i>'},
'Pustules (Phoenix)': {'type': 'organ/consumable', 'text': 'The aroma is tempting.<br\><br\><i>Drop chance: 2/24.</i>'},
'Rainbow Droppings (Phoenix)': {'type': 'organ/consumable', 'text': 'Consume: Archive this and roll 1d10. On 7+, gain +1 permanent speed. Otherwise, your heart explodes, killing you instantly.<br\><br\><i>Drop chance: 1/24.</i>'},
'Shimmering Halo (Phoenix)': {'type': 'organ', 'text': 'Curiously heavy.<br\><br\><i>Drop chance: 1/24.</i>'},
'Small Feathers (Phoenix)': {'type': 'hide', 'text': 'Soft interior with razor sharp edges.<br\><br\><i>Drop chance: 3/24.</i>'},
'Small Hand Parasites (Phoenix)': {'type': 'organ', 'text': 'Still wriggling.<br\><br\><i>Drop chance: 1/24.</i>'},
'Tail Feathers (Phoenix)': {'type': 'hide', 'text': 'Lighter than air.<br\><br\><i>Drop chance: 3/24.</i>'},
'Wishbone (Phoenix)': {'type': 'bone', 'text': 'A delicate bone with a strange aura.<br\><br\><i>Drop chance: 1/24.</i>'},

'Beast Steak (Screaming Antelope)': {'type': 'organ/consumable', 'text': 'Shockingly appetizing.<br\><br\><i>Drop chance: 2/16.</i>'},
'Bladder (Screaming Antelope)': {'type': 'organ/consumable', 'text': 'Smells like urine.<br\><br\><i>Drop chance: 1/16.</i>'},
'Large Flat Tooth (Screaming Antelope)': {'type': 'bone', 'text': 'When you gain this, a survivor of your choice gains +1 insanity. It\'s surface is rough and bumpy.<br\><br\><i>Drop chance: 2/16.</i>'},
'Muscly Gums (Screaming Antelope)': {'type': 'organ/consumable', 'text': 'Difficult to pry apart.<br\><br\><i>Drop chance: 1/16.</i>'},
'Pelt (Screaming Antelope)': {'type': 'hide', 'text': 'Coarse and warm.<br\><br\><i>Drop chance: 4/16.</i>'},
'Screaming Brain (Screaming Antelope)': {'type': 'organ/consumable', 'text': 'Consume: Archive this and gain survival up to the current limit.<br\><br\><i>Drop chance: 1/16.</i>'},
'Shank Bone (Screaming Antelope)': {'type': 'bone', 'text': 'Strangely jointed.<br\><br\><i>Drop chance: 4/16.</i>'},
'Spiral Horn (Screaming Antelope)': {'type': 'bone', 'text': 'Moans balefully when blown.<br\><br\><i>Drop chance: 1/16.</i>'},

'Arachnid Heart (Spidicules)': {'type': 'organ', 'text': 'Cold to the touch, even when freshly removed.<br\><br\><i>Drop chance: 1/14.</i>'},
'Chitin (Spidicules)': {'type': 'hide', 'text': 'A flaky, bitter-smelling husk.<br\><br\><i>Drop chance: 1/14.</i>'},
'Exoskeleton (Spidicules)': {'type': 'hide', 'text': 'Malleable, interlocking plates.<br\><br\><i>Drop chance: 1/14.</i>'},
'Eyeballs (Spidicules)': {'type': 'organ', 'text': 'Each points in a different direction.<br\><br\><i>Drop chance: 1/14.</i>'},
'Large Appendage (Spidicules)': {'type': 'bone', 'text': 'Could come in handy.<br\><br\><i>Drop chance: 2/14.</i>'},
'Serrated Fangs (Spidicules)': {'type': 'bone', 'text': '<br\><br\><i>Drop chance: 1/14.</i>'},
'Small Appendages (Spidicules)': {'type': 'hide', 'text': 'The inner hands look surprisingly human.<br\><br\><i>Drop chance: 2/14.</i>'},
'Spinnerets (Spidicules)': {'type': 'organ/scrap', 'text': 'More complex than any device.<br\><br\><i>Drop chance: 1/14.</i>'},
'Stomach (Spidicules)': {'type': 'organ', 'text': 'Consume: Archive this card to gain +1 Hunt XP.<br\><br\><i>Drop chance: 1/14.</i>'},
'Thick Web Silk (Spidicules)': {'type': 'silk/hide', 'text': 'Impossible to pierce.<br\><br\><i>Drop chance: 1/14.</i>'},
'Unlaid Eggs (Spidicules)': {'type': 'organ/consumable', 'text': 'During the settlement phase, you may consume and archive these delicious little eggs to gain 10 survival.<br\><br\><i>Drop chance: 1/14.</i>'},
'Venom Sac (Spidicules)': {'type': 'organ/consumable', 'text': 'Consume: Archive this card and roll 1d10. On a 1-5, you die instantly. On a 6+, gain the Death Touch Secret Fighting Art.<br\><br\><i>Drop chance: 1/14.</i>'},

'Black Lens (Sunstalker)': {'type': 'organ', 'text': 'These eyes are filled with a savory, gluey substance that dries when exposed to air.<br\><br\><i>Drop chance: 1/24.</i>'},
'Brain Root (Sunstalker)': {'type': 'organ', 'text': 'The strands of the root are strong and elastic. The meat on top is useless.<br\><br\><i>Drop chance: 1/24.</i>'},
'Cycloid Scales (Sunstalker)': {'type': 'hide', 'text': 'Extremely reflective and colorful.<br\><br\><i>Drop chance: 5/24.</i>'},
'Fertility Tentacle (Sunstalker)': {'type': 'organ', 'text': 'This tube-like appendage has a cavity at the base that stores eggs.<br\><br\><i>Drop chance: 1/24.</i>'},
'Huge Sunteeth (Sunstalker)': {'type': 'bone', 'text': 'These tough but light teeth are made of hundreds of thin layers of bone, separated by rows of dicot stems.<br\><br\><i>Drop chance: 3/24.</i>'},
'Inner Shadow Skin (Sunstalker)': {'type': 'hide', 'text': 'This soft, yet rubbery material blocks light.<br\><br\><i>Drop chance: 1/24.</i>'},
'Prismatic Gills (Sunstalker)': {'type': 'organ', 'text': 'When you gain this, gain the Emotionless disorder. The gills emit a fuzzy color trail.<br\><br\><i>Drop chance: 1/24.</i>'},
'Shadow Ink Gland (Sunstalker)': {'type': 'organ', 'text': 'The ink can be used to paint shadows that vanish in lantern light.<br\><br\><i>Drop chance: 1/24.</i>'},
'Shadow Tentacles (Sunstalker)': {'type': 'organ/hide', 'text': 'When you gain this during the hunt or showdown, return it to the resource deck and draw again if any survivors are blind.<br\><br\><i>Drop chance: 2/24.</i>'},
'Shark Tongue (Sunstalker)': {'type': 'organ', 'text': 'So slippery that it\'s hard to hold!<br\><br\><i>Drop chance: 1/24.</i>'},
'Small Sunteeth (Sunstalker)': {'type': 'bone', 'text': 'Unlike the large sunteeth, these are extremely sharp and clean.<br\><br\><i>Drop chance: 3/24.</i>'},
'Stink Lung (Sunstalker)': {'type': 'organ', 'text': 'When squeezed, a funny noise emerges followed by a tantalizing aroma.<br\><br\><i>Drop chance: 1/24.</i>'},
'Sunshark Blubber (Sunstalker)': {'type': 'organ', 'text': 'When inflated with air, this blubber gently floats.<br\><br\><i>Drop chance: 1/24.</i>'},
'Sunshark Bone (Sunstalker)': {'type': 'bone', 'text': 'The center is filled with water.<br\><br\><i>Drop chance: 1/24.</i>'},
'Sunshark Fin (Sunstalker)': {'type': 'bone/hide', 'text': 'Removing the slimy hands reveals a curable, viscous substance.<br\><br\><i>Drop chance: 1/24.</i>'},

'Curious Hand (White Lion)': {'image':'true', 'type': 'hide', 'text': 'When you gain this, a random survivor gains +1 insanity. Holding this fills you with sadness.<br\><br\><i>Drop chance: 1/19.</i>'},
'Eye of Cat (White Lion)': {'image':'true', 'type': 'organ/consumable', 'text': 'A perfectly preserved eye.<br\><br\><i>Drop chance: 1/19.</i>'},
'Golden Whiskers (White Lion)': {'image':'true', 'type': 'organ', 'text': 'These whiskers are tough!<br\><br\><i>Drop chance: 1/19.</i>'},
'Great Cat Bones (White Lion)': {'image':'true', 'type': 'bone', 'text': 'Strong and surprisingly light.<br\><br\><i>Drop chance: 4/19.</i>'},
'Lion Claw (White Lion)': {'image':'true', 'type': 'bone', 'text': 'A razor-sharp, retractable claw.<br\><br\><i>Drop chance: 3/19.</i>'},
'Lion Tail (White Lion)': {'image':'true', 'type': 'hide', 'text': 'It\'s surprisingly heavy.<br\><br\><i>Drop chance: 1/19.</i>'},
'Lion Testes (White Lion)': {'image':'true', 'type': 'organ/consumable', 'text': 'A hefty pair of nuts.<br\><br\><i>Drop chance: 1/19.</i>'},
'Shimmering Mane (White Lion)': {'image':'true', 'type': 'hide', 'text': 'Archive this to gain 2 basic hide resources. It shimmers in the lantern light.<br\><br\><i>Drop chance: 1/19.</i>'},
'Sinew (White Lion)': {'image':'true', 'type': 'organ', 'text': 'These stringy guts are quite useful.<br\><br\><i>Drop chance: 2/19.</i>'},
'White Fur (White Lion)': {'image':'true', 'type': 'hide', 'text': 'Luxurious and soft to the touch.<br\><br\><i>Drop chance: 4/19.</i>'},

'qqq (Basic)': {'label': '??? (Basic)', 'image': 'true', 'type': 'organ/bone/hide/consumable', 'text': 'You have no idea what monster bit this is. Can be used as a bone, organ, or hide!<br\><br\><i>Drop chance: 2/21.</i>'},
'Broken Lantern (Basic)': {'image': 'true', 'type': 'scrap', 'text': 'Remains of an extinguished lantern.<br\><br\><i>Drop chance: 2/21.</i>'},
'Love Juice (Basic)': {'image': 'true', 'type': 'organ/consumable', 'text': 'During the settlement phase, you may archive this to triggrer Intimacy story event. Nominated survivors must be able to consume.<br\><br\><i>Drop chance: 2/21.</i>'},
'Monster Bone (Basic)': {'image': 'true', 'type': 'bone', 'text': 'A bone suitable for crafting.<br\><br\><i>Drop chance: 4/21.</i>'},
'Monster Hide (Basic)': {'image': 'true', 'type': 'hide', 'text': 'The skin of a beast.<br\><br\><i>Drop chance: 7/21.</i>'},
'Monster Organ (Basic)': {'image': 'true', 'type': 'organ/consumable', 'text': 'If you consume this, archive this card. Roll 1d10. On a result of 6+, you contract a parasite. Archive all consumable gear in your grid now.<br\><br\><i>Drop chance: 3/21.</i>'},
'Skull (Basic)': {'image': 'true', 'type': 'bone', 'text': 'When you gain this, a survivor of your choice gains +1 insanity.<br\><br\><i>Drop chance: 1/21.</i>'},

'1,000 Year Sunspot (Sunstalker/Strange)': {'type': 'bone/organ', 'text': ''},
'3,000 Year Sunspot (Sunstalker/Strange)': {'type': 'bone/organ/scrap', 'text': ''},
'Active Thyroid (Gorm/Strange)': {'type': 'organ/consumable', 'text': ''},
'Black Lichen (Strange)': {'type': 'bone/organ/hide/consumable/other', 'text': ''},
'Blistering Plasma Fruit (Lonely Tree/Strange)': {'type': 'organ/consumable', 'text': ''},
'Bugfish (Sunstalker/Strange)': {'type': 'fish/organ', 'text': ''},
'Canopic Jar (Lion God/Strange)': {'type': 'organ/scrap', 'text': ''},
'Cocoon Membrane (Strange)': {'type': 'organ/other', 'text': ''},
'Crimson Vial (Manhunter/Strange)': {'type': 'iron/consumable', 'text': ''},
'Crystal Sword Mold (Slenderman/Strange)': {'type': 'scrap/iron', 'text': ''},
'Dark Water (Slenderman/Strange)': {'type': 'other', 'text': ''},
'Drifting Dream Fruit (Lonely Tree/Strange)': {'type': 'consumable', 'text': ''},
'Elder Cat Teeth (White Lion/Strange)': {'type': 'bone', 'text': ''},
'Fresh Acanthus (Strange)': {'type': 'herb', 'text': ''},
'Gormite (Gorm/Strange)': {'type': 'scrap/iron', 'text': ''},
'Hagfish (Sunstalker/Strange)': {'type': 'fish/bone/hide', 'text': ''},
'Iron (Strange)': {'type': 'scrap/iron', 'text': ''},
'Jagged Marrow Fruit (Lonely Tree/Strange)': {'type': 'bone/scrap/consumable', 'text': ''},
'Jowls (Sunstalker/Strange)': {'type': 'fish/iron', 'text': ''},
'Lantern Tube (Strange)': {'type': 'organ/scrap', 'text': ''},
'Leather (Strange)': {'type': 'hide/leather', 'text': ''},
'Legendary Horns (Screaming Antelope/Strange)': {'type': 'bone/scrap', 'text': ''},
'Lonely Fruit (Lonely Tree/Strange)': {'type': 'consumable', 'text': ''},
'Old Blue Box (Lion God/Strange)': {'type': 'scrap', 'text': ''},
'Perfect Crucible (Strange)': {'type': 'iron', 'text': ''},
'Phoenix Crest (Phoenix/Strange)': {'type': 'organ', 'text': ''},
'Pituitary Gland (Dragon King/Strange)': {'type': 'organ', 'text': ''},
'Porous Flesh Fruit (Lonely Tree/Strange)': {'type': 'hide/consumable', 'text': ''},
'Preserved Caustic Dung (Dung Beetle Knight/Strange)': {'type': 'organ/consumable/dung', 'text': ''},
'Pure Bulb (Gorm/Strange)': {'type': '', 'text': 'organ'},
'Radiant Heart (Dragon King/Strange)': {'type': 'organ', 'text': ''},
'Red Vial (Manhunter/Strange)': {'type': 'consumable', 'text': ''},
'Salt (Sunstalker/Strange)': {'type': 'salt', 'text': ''},
'Scell (Dung Beetle Knight/Strange)': {'type': 'organ/consumable', 'text': ''},
'Sarcophagus (Lion God/Strange)': {'type': 'iron', 'text': ''},
'Second Heart (Screaming Antelope/Strange)': {'type': 'organ/bone', 'text': ''},
'Shining Liver (Dragon King/Strange)': {'type': 'organ', 'text': ''},
'Silken Nervous System (Spidicules/Strange)': {'type': 'organ', 'text': ''},
'Silver Urn (Lion God/Strange)': {'type': 'bone/scrap', 'text': ''},
'Stomach Lining (Gorm/Strange)': {'type': 'organ', 'text': ''},
'Sunstones (Sunstalker/Strange)': {'type': 'bone', 'text': ''},
'Triptych (Lion God/Strange)': {'type': 'hide/scrap', 'text': ''},
'Web Silk (Spidicules/Strange)': {'type': 'silk', 'text': ''},

'Metal Face (Strange)': {'type':'scrap', 'text': 'During the settlement phase, you may archive 3 <b>Metal Face</b> strange resources to add 1 <b>Storm Helmet</b> rare gear to settlement storage.'}
}

module.exports = {
 texts,
}
