const event_img = imageHTML('images/icons/book', '0.9em;display:inline;vertical-allign:bottom')

const texts = {
'Cabled Vein': {'label':'', 'group_name':'Dragon King', 'type': 'organ', 'text': '<i>A dense bundle of bloody tubes.</i><br /><br />Drop chance: 2/21.'},
'Dragon Iron': {'type': 'iron', 'group_name':'Dragon King', 'text': '<i>It feels heavy, but when dropped, falls as slowly as a feather.</i><br /><br />Drop chance: 1/21.'},
'Hardened Ribs': {'type': 'bone', 'group_name':'Dragon King', 'text': '<i>Strong, flexible, and hollow.</i><br /><br />Drop chance: 1/21.'},
'Horn Fragment': {'type': 'bone', 'group_name':'Dragon King', 'text': '<i>Nearby speech causes them to resonate.</i><br /><br />Drop chance: 4/21.'},
'Husk': {'type': 'hide', 'group_name':'Dragon King', 'text': '<i>A decaying layer of former skin.</i><br /><br />Drop chance: 3/21.'},
'Kings Claws': {'label':'King\'s Claws', 'type': 'bone', 'group_name':'Dragon King', 'text': '<i>Disturbingly warm, and sharp enough to draw blood with a touch.</i><br /><br />Drop chance: 4/21.'},
'Kings Tongue': {'label':'King\'s Tongue', 'type': 'hide', 'group_name':'Dragon King', 'text': '<i>Smooth, dry, and sharp.</i><br /><br />Drop chance: 1/21.'},
'Radioactive Drug': {'type': 'organ/scrap', 'group_name':'Dragon King', 'text': '<i>Gives off smoke with an acrid odor.</i><br /><br />Drop chance: 2/21.'},
'Veined Wing': {'type': 'hide', 'group_name':'Dragon King', 'text': '<i>Blood drips from it at a constant rate.</i><br /><br />Drop chance: 3/21.'},

'Beetle Horn': {'type': 'bone', 'group_name':'Dung Beetle Knight', 'text': '<b>Brain Stimulation</b> <i style="color:#999">(requires Scarification)</i><br />Archive and Roll <b>1d10</b>:<br /> <b style=\"color:#cc0;\">1-4</b><div style="font-size:0.9em;display: inline;"> - Your brain is punctured and you die.</div><br /> <b style=\"color:#cc0;\">5+</b><div style="font-size:0.9em;display: inline;"> - Gain the benefits of <b>Age 1</b> and <b>Age 2</b> without gaining Hunt XP. Brain Stimulation ignores the "once a lifetime" rule on the '+event_img+'<b>Age</b>.</div><br /><br />Drop chance: 1/11.'},
'Century Fingernails': {'type': 'bone', 'group_name':'Dung Beetle Knight', 'text': '<i>These nails are never clipped. Instead, they are folded and hammered hundreds of times into an impossibly fine edge.</i><br /><br />Drop chance: 2/11.'},
'Century Shell': {'type': 'hide/iron', 'group_name':'Dung Beetle Knight', 'text': '<i>This ancient and mineral-rich armor plate is covered with razor wind scratches.</i><br /><br />You may spend this as if it were a Scarab Shell resource.<br /><br />Drop chance: 1/11.'},
'Compound Eye': {'type': 'organ/consumable', 'group_name':'Dung Beetle Knight', 'text': '<i>A cluster of differently colored eyes, each filled with a creamy, tangy syrup.</i><br /><br />If you have 3+ courage, you may consume and archive this to gain +3d10 insanity.<br /><br />Drop chance: 1/11.'},
'Elytra': {'type': 'bone/hide/organ', 'group_name':'Dung Beetle Knight', 'text': '<i>The ribbed underside of these large shells makes an ideal surface to grind weapons.</i><br /><br />A survivor may archive this to give all of their attacks in the next showdown Sharp.<br /><br />Drop chance: 1/11.'},
'Scarab Shell': {'type': 'hide', 'group_name':'Dung Beetle Knight', 'text': '<i>Cool and oily to the touch. Lantern light reveals a brilliant band of color dancing on its surface.</i><br /><br />Drop chance: 3/11.'},
'Scarab Wing': {'type': 'organ', 'group_name':'Dung Beetle Knight', 'text': '<i>When soaked in water, these vein-filled wings gain some elasticity.</i><br /><br />Drop chance: 1/11.'},
'Underplate Fungus': {'type': 'herb/hide/consumable', 'group_name':'Dung Beetle Knight', 'text': '<i>A corkscrew-shaped fungus that grows in the empty channels between the Dung Beetle Knight\'s armor plating.</i><br /><br />Drop chance: 1/11.'},

'Lantern Bloom': {'type': 'flower/hide', 'group_name':'Flower Knight', 'text': '<b>Perishable</b>.<br />You may <b>consume</b> and archive this during the showdown to gain +3 luck tokens, -1 permanent luck, and the <b>Flower Addiction</b> disorder.<br /><br />Drop chance: 3/14.'},
'Lantern Bud': {'type': 'flower/scrap', 'group_name':'Flower Knight', 'text': '<b>Perishable</b>.<br />You may <b>consume</b> and archive this during the settlement phase to gain +3{image@images/icons/endeavors}, skip the next hunt, and gain the <b>Flower Addiction</b> disorder.<br /><br />Drop chance: 1/14.'},
'Osseous Bloom': {'type': 'flower/bone', 'group_name':'Flower Knight', 'text': '<b>Perishable</b>.<br />You may <b>consume</b> and archive this during the showdown to remove all your bleeding and negative attribute tokens and gain the <b>Flower Addiction</b> disorder.<br /><br />Drop chance: 5/14.'},
'Sighing Bloom': {'type': 'flower/organ', 'group_name':'Flower Knight', 'text': '<b>Perishable</b>.<br />You may <b>consume</b> and archive this during the showdown to gain 3 survival, 3 insanity, and the <b>Flower Addiction</b> disorder.<br /><br />Drop chance: 3/14.'},
'Warbling Bloom': {'type': 'flower/hide', 'group_name':'Flower Knight', 'text': '<b>Perishable</b>.<br />You may plant this during the settlement phase to archive it and gain +1 population. The survivor is born with the <b>Flower Addiction</b> disorder and a face just like the Warbling Bloom\'s.<br /><br />Drop chance: 2/14.'},

'Acid Gland': {'type': 'organ', 'group_name':'Gorm', 'text': '<i>Melts skin.</i><br /><br />Drop chance: 1/21.'},
'Dense Bone': {'type': 'bone', 'group_name':'Gorm', 'text': '<i>Sturdy.</i><br /><br />Drop chance: 2/21.'},
'Gorm Brain': {'type': 'organ', 'group_name':'Gorm', 'text': '<i>Shockingly small.</i><br /><br />Drop chance: 1/21.'},
'Handed Skull': {'type': 'bone', 'group_name':'Gorm', 'text': '<i>Incomparably dense.</i><br /><br />Drop chance: 1/21.'},
'Jiggling Lard': {'type': 'organ/hide', 'group_name':'Gorm', 'text': '<i>Thick, quivering mass.</i><br /><br />Drop chance: 2/21.'},
'Mammoth Hand': {'type': 'bone/hide/organ', 'group_name':'Gorm', 'text': '<i>An enormous, leathery glove.</i><br /><br />Drop chance: 2/21.'},
'Meaty Rib': {'type': 'bone/organ', 'group_name':'Gorm', 'text': '<i>Useful and delicious.</i><br /><br />Drop chance: 2/21.'},
'Milky Eye': {'type': 'organ', 'group_name':'Gorm', 'text': '<i>When this resource is gained, select a survivor to gain +3 insanity.<br /><br />Drop chance: 1/21.'},
'Stout Heart': {'type': 'organ', 'group_name':'Gorm', 'text': '<i>A titanic pump.</i><br /><br />Drop chance: 2/21.'},
'Stout Hide': {'type': 'hide', 'group_name':'Gorm', 'text': '<i>Touch, wrinkly skin.</i><br /><br />Drop chance: 4/21.'},
'Stout Kidney': {'type': 'organ', 'group_name':'Gorm', 'text': '<b>Consume</b>: archive this and roll 1d10:<br /> <b style=\"color:#cc0;\">1-5</b><div style="font-size:0.9em;display: inline;"> - reduce your survival to 0.</div><br /><b style=\"color:#cc0;\">6+</b><div style="font-size:0.9em;display: inline;"> - gain 10 survival.</div><br /><br />Drop chance: 2/21.'},
'Stout Vertebrae': {'type': 'bone', 'group_name':'Gorm', 'text': '<i>Hefty and intricately joined.</i><br /><br />Drop chance: 1/21.'},

'Bird Beak': {'type': 'bone', 'group_name':'Phoenix', 'text': '<i>Surprisingly toothy.</i><br /><br />Drop chance: 1/24.'},
'Black Skull': {'type': 'iron/skull/bone', 'group_name':'Phoenix', 'text': '<i>Aged to perfection.</i><br /><br />Drop chance: 1/24.'},
'Hollow Wing Bones': {'type': 'bone', 'group_name':'Phoenix', 'text': '<i>Delicate and finely balanced.</i><br /><br />Drop chance: 3/24.'},
'Muculent Droppings': {'type': 'organ', 'group_name':'Phoenix', 'text': '<i>Delicately scented, papery husk.</i><br /><br />Drop chance: 3/24.'},
'Phoenix Eye': {'type': 'organ/scrap', 'group_name':'Phoenix', 'text': '<i>Filled with a thick, metallic liquid.</i><br /><br />Drop chance: 1/24.'},
'Phoenix Finger': {'type': 'bone', 'group_name':'Phoenix', 'text': 'When you gain this, a survivor of your choice gains +3 insanity.<br /><br />Drop chance: 2/24.'},
'Phoenix Whisker': {'type': 'hide', 'group_name':'Phoenix', 'text': '<i>Silky, yet robust.</i><br /><br />Drop chance: 1/24.'},
'Pustules': {'type': 'organ/consumable', 'group_name':'Phoenix', 'text': '<i>The aroma is tempting.</i><br /><br />Drop chance: 2/24.'},
'Rainbow Droppings': {'type': 'organ/consumable', 'group_name':'Phoenix', 'text': '<b>Consume</b>: Archive this and roll 1d10:<br /><b style=\"color:#cc0;\">1-6</b><div style="font-size:0.9em;display: inline;"> - your heart explodes, killing you instantly.</div><br /><b style=\"color:#cc0;\">7+</b><div style="font-size:0.9em;display: inline;"> - gain +1 permanent speed.</div><br /><br />Drop chance: 1/24.'},
'Shimmering Halo': {'type': 'organ', 'group_name':'Phoenix', 'text': '<i>Curiously heavy.</i><br /><br />Drop chance: 1/24.'},
'Small Feathers': {'type': 'hide', 'group_name':'Phoenix', 'text': '<i>Soft interior with razor sharp edges.</i><br /><br />Drop chance: 3/24.'},
'Small Hand Parasites': {'type': 'organ', 'group_name':'Phoenix', 'text': '<i>Still wriggling.</i><br /><br />Drop chance: 1/24.'},
'Tail Feathers': {'type': 'hide', 'group_name':'Phoenix', 'text': '<i>Lighter than air.</i><br /><br />Drop chance: 3/24.'},
'Wishbone': {'type': 'bone', 'group_name':'Phoenix', 'text': '<i>A delicate bone with a strange aura.</i><br /><br />Drop chance: 1/24.'},

'Beast Steak': {'type': 'organ/consumable', 'group_name':'Screaming Antelope', 'text': '<i>Shockingly appetizing.</i><br /><br />Drop chance: 2/16.'},
'Bladder': {'type': 'organ/consumable', 'group_name':'Screaming Antelope', 'text': '<i>Smells like urine.</i><br /><br />Drop chance: 1/16.'},
'Large Flat Tooth': {'type': 'bone', 'group_name':'Screaming Antelope', 'text': '<i>It\'s surface is rough and bumpy.</i><br /><br />When you gain this, a survivor of your choice gains +1 insanity.<br /><br />Drop chance: 2/16.'},
'Muscly Gums': {'type': 'organ/consumable', 'group_name':'Screaming Antelope', 'text': '<i>Difficult to pry apart.</i><br /><br />Drop chance: 1/16.'},
'Pelt': {'type': 'hide', 'group_name':'Screaming Antelope', 'text': '<i>Coarse and warm.</i><br /><br />Drop chance: 4/16.'},
'Screaming Brain': {'type': 'organ/consumable', 'group_name':'Screaming Antelope', 'text': '<b>Consume</b>: Archive this and gain survival up to the current limit.<br /><br />Drop chance: 1/16.'},
'Shank Bone': {'type': 'bone', 'group_name':'Screaming Antelope', 'text': '<i>Strangely jointed.</i><br /><br />Drop chance: 4/16.'},
'Spiral Horn': {'type': 'bone', 'group_name':'Screaming Antelope', 'text': '<i>Moans balefully when blown.</i><br /><br />Drop chance: 1/16.'},

'Arachnid Heart': {'type': 'organ', 'group_name':'Spidicules', 'text': '<i>Cold to the touch, even when freshly removed.</i><br /><br />Drop chance: 1/14.'},
'Chitin': {'type': 'hide', 'group_name':'Spidicules', 'text': '<i>A flaky, bitter-smelling husk.</i><br /><br />Drop chance: 1/14.'},
'Exoskeleton': {'type': 'hide', 'group_name':'Spidicules', 'text': '<i>Malleable, interlocking plates.</i><br /><br />Drop chance: 1/14.'},
'Eyeballs': {'type': 'organ', 'group_name':'Spidicules', 'text': '<i>Each points in a different direction.</i><br /><br />Drop chance: 1/14.'},
'Large Appendage': {'type': 'bone', 'group_name':'Spidicules', 'text': '<i>Could come in handy.</i><br /><br />Drop chance: 2/14.'},
'Serrated Fangs': {'type': 'bone', 'group_name':'Spidicules', 'text': '<b>Razor Push-ups</b> <i style="color:#999">(requires Nightmare Training)</i> - Roll 1d10<br /><b style=\"color:#cc0;\">1-3</b><div style="font-size:0.9em;display: inline;"> - Gain random disorder.</div><br /><b style=\"color:#cc0;\">4+</b><div style="font-size:0.9em;display: inline;"> - Gain +1 permanent Strength. <i>The fangs are crushed;</i> archive this card.</div><br /><br />Drop chance: 1/14.'},
'Small Appendages': {'type': 'hide', 'group_name':'Spidicules', 'text': '<i>The inner hands look surprisingly human.</i><br /><br />Drop chance: 2/14.'},
'Spinnerets': {'type': 'organ/scrap', 'group_name':'Spidicules', 'text': '<i>More complex than any device.</i><br /><br />Drop chance: 1/14.'},
'Stomach': {'type': 'organ', 'group_name':'Spidicules', 'text': '<b>Consume</b>: Archive this card to gain +1 Hunt XP.<br /><br />Drop chance: 1/14.'},
'Thick Web Silk': {'type': 'silk/hide', 'group_name':'Spidicules', 'text': '<i>Impossible to pierce.</i><br /><br />Drop chance: 1/14.'},
'Unlaid Eggs': {'type': 'organ/consumable', 'group_name':'Spidicules', 'text': 'During the settlement phase, you may <b>consume</b> and archive these delicious little eggs to gain 10 survival.<br /><br />Drop chance: 1/14.'},
'Venom Sac': {'type': 'organ/consumable', 'group_name':'Spidicules', 'text': '<b>Consume</b>: Archive this card and roll 1d10.<br /><b style=\"color:#cc0;\">1-5</b><div style="font-size:0.9em;display: inline;"> - you die instantly.</div><br /><b style=\"color:#cc0;\">6+</b><div style="font-size:0.9em;display: inline;"> - gain the <b>Death Touch</b> Secret Fighting Art.</div><br /><br />Drop chance: 1/14.'},

'Black Lens': {'type': 'organ', 'group_name':'Sunstalker', 'text': '<i>These eyes are filled with a savory, gluey substance that dries when exposed to air.</i><br /><br />Drop chance: 1/24.'},
'Brain Root': {'type': 'organ', 'group_name':'Sunstalker', 'text': '<i>The strands of the root are strong and elastic. The meat on top is useless.</i><br /><br />Drop chance: 1/24.'},
'Cycloid Scales': {'type': 'hide', 'group_name':'Sunstalker', 'text': '<i>Extremely reflective and colorful.</i><br /><br />Drop chance: 5/24.'},
'Fertility Tentacle': {'type': 'organ', 'group_name':'Sunstalker', 'text': '<i>This tube-like appendage has a cavity at the base that stores eggs.</i><br /><br />Drop chance: 1/24.'},
'Huge Sunteeth': {'type': 'bone', 'group_name':'Sunstalker', 'text': '<i>These tough but light teeth are made of hundreds of thin layers of bone, separated by rows of dicot stems.</i><br /><br />Drop chance: 3/24.'},
'Inner Shadow Skin': {'type': 'hide', 'group_name':'Sunstalker', 'text': '<i>This soft, yet rubbery material blocks light.</i><br /><br />Drop chance: 1/24.'},
'Prismatic Gills': {'type': 'organ', 'group_name':'Sunstalker', 'text': '<i>When you gain this, gain the Emotionless disorder. The gills emit a fuzzy color trail.</i><br /><br />Drop chance: 1/24.'},
'Shadow Ink Gland': {'type': 'organ', 'group_name':'Sunstalker', 'text': '<i>The ink can be used to paint shadows that vanish in lantern light.</i><br /><br />Drop chance: 1/24.'},
'Shadow Tentacles': {'type': 'organ/hide', 'group_name':'Sunstalker', 'text': '<i>When you gain this during the hunt or showdown, return it to the resource deck and draw again if any survivors are <b>blind</b>.<br /><br />Drop chance: 2/24.'},
'Shark Tongue': {'type': 'organ', 'group_name':'Sunstalker', 'text': '<i>So slippery that it\'s hard to hold!</i><br /><br />Drop chance: 1/24.'},
'Small Sunteeth': {'type': 'bone', 'group_name':'Sunstalker', 'text': '<i>Unlike the large sunteeth, these are extremely sharp and clean.</i><br /><br />Drop chance: 3/24.'},
'Stink Lung': {'type': 'organ', 'group_name':'Sunstalker', 'text': '<i>When squeezed, a funny noise emerges followed by a tantalizing aroma.</i><br /><br />Drop chance: 1/24.'},
'Sunshark Blubber': {'type': 'organ', 'group_name':'Sunstalker', 'text': '<i>When inflated with air, this blubber gently floats.</i><br /><br />Drop chance: 1/24.'},
'Sunshark Bone': {'type': 'bone', 'group_name':'Sunstalker', 'text': '<i>The center is filled with water.</i><br /><br />Drop chance: 1/24.'},
'Sunshark Fin': {'type': 'bone/hide', 'group_name':'Sunstalker', 'text': '<i>Removing the slimy hands reveals a curable, viscous substance.</i><br /><br />Drop chance: 1/24.'},

'Curious Hand': {'image':'true', 'group_name':'White Lion', 'type': 'hide', 'text': ' <i>Holding this fills you with sadness.</i><br /><br />When you gain this, a random survivor gains +1 insanity.<br /><br />Drop chance: 1/19.'},
'Eye of Cat': {'image':'true', 'group_name':'White Lion', 'type': 'organ/consumable', 'text': '<i>A perfectly preserved eye.</i><br /><br />Drop chance: 1/19.'},
'Golden Whiskers': {'image':'true', 'group_name':'White Lion', 'type': 'organ', 'text': '<i>These whiskers are tough!</i><br /><br />Drop chance: 1/19.'},
'Great Cat Bones': {'image':'true', 'group_name':'White Lion', 'type': 'bone', 'text': '<i>Strong and surprisingly light.</i><br /><br />Drop chance: 4/19.'},
'Lion Claw': {'image':'true', 'group_name':'White Lion', 'type': 'bone', 'text': '<i>A razor-sharp, retractable claw.</i><br /><br />Drop chance: 3/19.'},
'Lion Tail': {'image':'true', 'group_name':'White Lion', 'type': 'hide', 'text': '<i>It\'s surprisingly heavy.</i><br /><br />Drop chance: 1/19.'},
'Lion Testes': {'image':'true', 'group_name':'White Lion', 'type': 'organ/consumable', 'text': '<i>A hefty pair of nuts.</i><br /><br />Drop chance: 1/19.'},
'Shimmering Mane': {'image':'true', 'group_name':'White Lion', 'type': 'hide', 'text': ' <i>It shimmers in the lantern light.</i><br /><br />Archive this to gain 2 basic hide resources.<br /><br />Drop chance: 1/19.'},
'Sinew': {'image':'true', 'group_name':'White Lion', 'type': 'organ', 'text': '<i>These stringy guts are quite useful.</i><br /><br />Drop chance: 2/19.'},
'White Fur': {'image':'true', 'group_name':'White Lion', 'type': 'hide', 'text': '<i>Luxurious and soft to the touch.</i><br /><br />Drop chance: 4/19.'},

'qqq': {'label': '???', 'group_name':'Basic', 'image': 'true', 'type': 'organ/bone/hide/consumable', 'text': '<i>You have no idea what monster bit this is.</i><br /><br />Can be used as a bone, organ, or hide!<br /><br />Drop chance: 2/21.'},
'Broken Lantern': {'image': 'true', 'group_name':'Basic', 'type': 'scrap', 'text': '<i>Remains of an extinguished lantern.</i><br /><br />Drop chance: 2/21.'},
'Love Juice': {'image': 'true', 'group_name':'Basic', 'type': 'organ/consumable', 'text': 'During the settlement phase, you may archive this to trigger '+event_img+'<b>Intimacy</b>. Nominated survivors must be able to consume.<br /><br />Drop chance: 2/21.'},
'Monster Bone': {'image': 'true', 'group_name':'Basic', 'type': 'bone', 'text': '<i>A bone suitable for crafting.</i><br /><br />Drop chance: 4/21.'},
'Monster Hide': {'image': 'true', 'group_name':'Basic', 'type': 'hide', 'text': '<i>The skin of a beast.</i><br /><br />Drop chance: 7/21.'},
'Monster Organ': {'image': 'true', 'group_name':'Basic', 'type': 'organ/consumable', 'text': 'If you <b>consume</b> this, archive this card. Roll 1d10:<br /><b style=\"color:#cc0;\">6+</b><div style="font-size:0.9em;display: inline;"> - you contract a parasite. Archive all consumable gear in your grid now.</div><br /><br />Drop chance: 3/21.'},
'Skull': {'image': 'true', 'group_name':'Basic', 'type': 'bone', 'text': 'When you gain this, a survivor of your choice gains +1 insanity.<br /><br />Drop chance: 1/21.'},

'1,000 Year Sunspot': {'type': 'bone/organ', 'group_name':'Sunstalker, Strange',
                      'text': 'When you craft this, nominate a survivor. They suffer the <b>blind</b> severe injury from working with this resource.'},
'3,000 Year Sunspot': {'type': 'bone/organ/scrap', 'group_name':'Sunstalker, Strange',
                      'text': 'When you craft with this, nominate a survivor and roll <b>1d10</b>:<br /><b style=\"color:#cc0;\">5+</b><div style="font-size:0.9em;display: inline;"> - they get a terrible headache and die.</div>'},
'Active Thyroid': {'type': 'organ/consumable', 'group_name':'Gorm, Strange',
                      'text': '<b>Consume</b>: archive this and roll <b>1d10</b>:<br /><b style=\"color:#cc0;\">1-6</b><div style="font-size:0.9em;display: inline;"> - your heart explodes, killing you instantly.</div><br /><b style=\"color:#cc0;\">7+</b><div style="font-size:0.9em;display: inline;"> - gain +1 permanent speed.</div>'},
'Black Lichen': {'type': 'bone/organ/hide/consumable/other', 'group_name':'Strange',
                'text': '<i>Malleable, pungent and attractive.</i><br/><br/>You may <b>consume</b> this. If you do, your lips turn gray, your hair whitens, and you become infertile. Gain +1 courage, +1 understanding and suffer <b>destroyed genitals</b> severe waist injury.'},
'Blistering Plasma Fruit': {'type': 'organ/consumable', 'group_name':'Lonely Tree, Strange',
                'text': 'You may <b>consume</b> and archive this to gain the following ability.<br /><br /><b>Nightmare Blood</b>: Whenever you gain a bleeding token, add +1 to all hit locations.'},
'Bugfish': {'type': 'fish/organ', 'group_name':'Sunstalker, Strange',
                'text': '<b>Consume</b>: Gain +2 survival. <i>There is something in its belly!</i> Gain 1 random vermin and <b>consume</b> it immediately. Archive this card.'},
'Canopic Jar': {'type': 'organ/scrap', 'group_name':'Lion God, Strange',
                'text': 'When you gain this, remove 2 bleeding tokens.<br /><br />During the settlement phase, you may archive this to '+event_img+'<b>Death Reading</b>.'},
'Cocoon Membrane': {'type': 'organ/other', 'group_name':'Strange',
                'text': '<i>Thin copper hairs permeate this jellylike substance. Lanterns are repelled by the copper hairs, their light bending to avoid them.</i>'},
'Crimson Vial': {'type': 'iron/consumable', 'group_name':'Manhunter, Strange',
                'text': 'You may <b>consume</b> and archive this to remove all bleeding tokens and any severy injury of your choice.'},
'Crystal Sword Mold': {'type': 'scrap/iron', 'group_name':'Slenderman, Strange',
                'text': '<i>This strange crystal refracts light, concentrating it within a natural, sword-shaped chamber.</i>'},
'Dark Water': {'type': 'other', 'group_name':'Slenderman, Strange',
                'text': 'You may <b>consume</b> and archive this to remove all your disorders, then gain a random disorder.'},
'Drifting Dream Fruit': {'type': 'consumable', 'group_name':'Lonely Tree, Strange',
                'text': 'You may <b>consume</b> and archive this to select a Dream on the '+event_img+'<b>Birth of a Savior</b> and gain all associated abilities.'},
'Elder Cat Teeth': {'type': 'bone', 'group_name':'White Lion, Strange',
                'text': '<i>As sharp as they are strange</i>'},
'Fresh Acanthus': {'type': 'herb', 'group_name':'Strange',
                'text': 'Archive this to fully heal 1 hit location, including injury levels and armor points.'},
'Gormite': {'type': 'scrap/iron', 'group_name':'Gorm, Strange',
                'text': '<i>The toughest stuff known to man.</i>'},
'Hagfish': {'type': 'fish/bone/hide', 'group_name':'Sunstalker, Strange',
                'text': '<b>Consume</b>: Your hair turns gray and you gain +1 Hunt XP. Archive the card.'},
'Iron': {'type': 'scrap/iron', 'group_name':'Strange',
                'text': '<i>Harder than bone.</i>'},
'Jagged Marrow Fruit': {'type': 'bone/scrap/consumable', 'group_name':'Lonely Tree, Strange',
                'text': 'You may <b>consume</b> and archive this to gain the following ability.<br /><br /><b>Nightmare Spurs</b>: Once per showdown, you may spend all your survival (at least 1) to lose all your +1 strength tokens and gain that many +1 luck tokens.'},
'Jowls': {'type': 'fish/iron', 'group_name':'Sunstalker, Strange',
                'text': 'When you gain Jowls, it bites off your nose! If you have no nose, you die.<br /><br />If you have <b>Jowls</b>, <b>Hagfish</b>, and <b>Bugfish</b>, you are inspired! You may archive all 3 to gain the <b>Filleting Table</b> innovation.'},
'Lantern Tube': {'type': 'organ/scrap', 'group_name':'Strange',
                'text': '<i>A fleshy, muscle-lined tube.</i><br /><br />When you gain this, roll <b>1d10</b>:<br /><b style=\"color:#cc0;\">6+</b><div style="font-size:0.9em;display: inline;"> - you find something stuck inside! Add 1 <b>Broken Lantern</b> basic resource to the settlement\'s storage.</div>'},
'Leather': {'type': 'hide/leather', 'group_name':'Strange',
                'text': '<i>Never goes out of style</i>'},
'Legendary Horns': {'type': 'bone/scrap', 'group_name':'Screaming Antelope, Strange',
                'text': '<i>Holding them fills you with power.</i>'},
'Lonely Fruit': {'type': 'consumable', 'group_name':'Lonely Tree, Strange',
                'text': 'During the settlement phase, you may <b>consume</b> and archive this to '+event_img+'<b>Lonely Lady</b>.'},
'Old Blue Box': {'type': 'scrap', 'group_name':'Lion God, Strange',
                'text': 'During the settlement phase, you may archive this to '+event_img+'<b>Death Reading</b>.'},
'Perfect Crucible': {'type': 'iron', 'group_name':'Strange',
                'text': 'When you craft with Perfect Crucible, an ancient bacteria is released into the air. Suffer -1d10 population and archive this card.'},
'Phoenix Crest': {'type': 'organ', 'group_name':'Phoenix, Strange',
                'text': '<i>Firm and supple.</i>'},
'Pituitary Gland': {'type': 'organ', 'group_name':'Dragon King, Strange',
                'text': '<b>Consume</b>: Archive this and roll <b>1d10</b>:<br /><b style=\"color:#cc0;\">1-3</b><div style="font-size:0.9em;display: inline;"> - you grow to gian size and die.</div><br /><b style=\"color:#cc0;\">4+</b><div style="font-size:0.9em;display: inline;"> - gain +1 permanent strength.</div>'},
'Porous Flesh Fruit': {'type': 'hide/consumable', 'group_name':'Lonely Tree, Strange',
                'text': 'You may consume and archive this to gain the following ability.<br /><br /><b>Nightmare Membrane</b>: You may spend {image@images/icons/movement} and {image@images/icons/activation} to exchange any 1 of your tokens for a +1 strength token.'},
'Preserved Caustic Dung': {'type': 'organ/consumable/dung', 'group_name':'Dung Beetle Knight, Strange',
                'text': '<i>The live cultures in this exotic mixture of matured dung have been preserved within a delicate, airtight jelly casing.</i>'},
'Pure Bulb': {'type': 'organ', 'group_name':'Gorm, Strange',
                'text': '<i>Don\'t stare at it.</i>'},
'Radiant Heart': {'type': 'organ', 'group_name':'Dragon King, Strange',
                'text': 'When you gain this resource, roll <b>1d10</b>:<br /><b style=\"color:#cc0;\">3+</b><div style="font-size:0.9em;display: inline;"> - you burst into flames and die.</div>'},
'Red Vial': {'type': 'consumable', 'group_name':'Manhunter, Strange',
                'text': 'You may <b>consume</b> and archive this to remove 2 bleeding tokens and gain +1 survival.'},
'Salt': {'type': 'salt', 'group_name':'Sunstalker, Strange',
                'text': '<i>When exposed to lantern light it evaporates, forming a crust.</i><br /><br />You may add this to any cooking recipe to gain +1 permanent strength in addition to the recipe\'s listed benefits.'},
'Scell': {'type': 'organ/consumable', 'group_name':'Dung Beetle Knight, Strange',
                'text': '<i>As the monster ages, this sticky and corrosive material builds between the thin layers of its scarab shells. It breaks down fecal product, preventing the knight\'s joints from locking up.</i><br /><br />During <b>Black Harvest</b>, a Restorer can make excellent use of a Scell, using it to nearly perfect the final step of the calcification process.'},
'Sarcophagus': {'type': 'iron', 'group_name':'Lion God, Strange',
                'text': '-2 movement while you have this.<br /><br />During the settlement phase, you may archive this to '+event_img+'<b>Death Reading</b>.'},
'Second Heart': {'type': 'organ/bone', 'group_name':'Screaming Antelope, Strange',
                'text': '<i>It still tries to bite you.</i>'},
'Shining Liver': {'type': 'organ', 'group_name':'Dragon King, Strange',
                'text': '<i>When exposed to light, it filters it into heat and become darker.</i>'},
'Silken Nervous System': {'type': 'organ', 'group_name':'Spidicules, Strange',
                'text': '<i>Separates into tiny golden treads.</i>'},
'Silver Urn': {'type': 'bone/scrap', 'group_name':'Lion God, Strange',
                'text': 'During the settlement phase, you may archive this to '+event_img+'<b>Death Reading</b>.'},
'Stomach Lining': {'type': 'organ', 'group_name':'Gorm, Strange',
                'text': '<i>Steadily expands and contracts.</i>'},
'Sunstones': {'type': 'bone', 'group_name':'Sunstalker, Strange',
                'text': '<i>Small and warm.</i>'},
'Triptych': {'type': 'hide/scrap', 'group_name':'Lion God, Strange',
                'text': 'When you gain this, gain +3 insanity.<br /><br />During the settlement phase, you may archive this to '+event_img+'<b>Death Reading</b>.'},
'Web Silk': {'type': 'silk', 'group_name':'Spidicules, Strange',
                'text': '<i>Impossible to tear.</i>'},

'Metal Face': {'type':'scrap', 'group_name':'Strange', 'text': '<i>A magnetic force emanates from the metal.</i><br /><br />During the settlement phase, you may archive 3 <b>Metal Face</b> strange resources to add 1 <b>Storm Helmet</b> rare gear to settlement storage.'},

'Hooked Claw': {'type':'bone', 'group_name':'White Gigalion, Strange', 'text': '<i>Stained with flecks of ancient dried blood and bits of ossified hair.</i>'},

'Allisons Legacy': {'label':'Allison\'s Legacy', 'type': 'hide/other', 'group_name':'Strange',
                'text': '<i>A personal account detailing the selfless work of Allison, the Twilight Knight.</i><br/><br/>During the settlement phase, a survivor may spend {image@images/icons/endeavors} to read from the book. The secrets within are so profound, they gain the <b>Fear of the Dark</b> disorder.<br/><br/>If the book is read, all <b>Apprentices</b> gain +1 permanent strength. If a survivor with Twilight Sword proficiency has 8 weapon XP, they gain <b>Twilight Sword Mastery</b>.<br/><br/>Archive this card.'},
'Copper': {'type': 'scrap', 'group_name':'Strange',
                'text': '<i>Rarer than iron.</i>'},
'Lantern Nerve Bundle': {'type': 'organ/consumable', 'group_name':'Strange',
                'text': 'Archive this to put on an electrifying display of strength.<br/><br/><b style=\"color:#cc0;\">1-3</b><div style="font-size:0.9em;display: inline;"> - Lose 1 weapon proficieny level.</div><br /><b style=\"color:#cc0;\">4-8</b><div style="font-size:0.9em;display: inline;"> - gain +1 permanent strength.</div><br /><b style=\"color:#cc0;\">9+</b><div style="font-size:0.9em;display: inline;"> - Suffer 2 brain damage. Your Fist&Tooth attack gains <b>devastating</b> for the next showdwon with a quarry.</div>'},
'Skeletal Shards': {'type': 'bone', 'group_name':'Strange',
                'text': '<i>The pulsating, blue marrow appears soft and malleable, before hardening.</i><br/><br/>Skeletal Shards may be substituted in any recipe that requires a monster specific bone.'},
'Watcher Jelly': {'type': 'organ/consumable', 'group_name':'Strange',
                'text': '<b>Apply</b>: Archive this and roll <b>1d10</b>.<br/><br/><b style=\"color:#cc0;\">1-3</b><div style="font-size:0.9em;display: inline;"> - The substance hardens uncomfortably. Suffer -1 permanent movement.</div><br /><b style=\"color:#cc0;\">4-8</b><div style="font-size:0.9em;display: inline;"> - It hardens into a strong shell. When you <b>depart</b>, add +3 armor to the body location.</div><br /><b style=\"color:#cc0;\">9+</b><div style="font-size:0.9em;display: inline;"> - Gain +1 permanent evasion.</div>'},
'Whispering Whetstone': {'type': 'scrap/other', 'group_name':'Strange',
                'text': '<i>It whispers only to you.</i><br/><br/>{image@images/icons/endeavors}: Archive this to give one axe, sword, dagger, scythe, katana, or katar gear in the settlement storage <b>sharp</b>. Lasts until end of the next showdown. After archiving gain 1 <b>iron</b> strange resource.'},


'Destroyed Barb': {'type': 'bone', 'group_name':'Drifter Knight, Strange', 'text': '<i>Merely handling it draws blood.</i>'},
'Neurotoxin': {'type': 'organ', 'group_name':'Drifter Knight, Strange', 'text': '<i>Causes instant death to survivors and other vermin.</i>'},

'Bile duct': {'type': 'bone/hide/organ', 'group_name':'Drifter Knight', 'text': '<i>Ignore the fact that it has no stomach.</i><br /><br />Drop chance: 2/15.'},
'Exquisite Fabric': {'type': 'hide/silk', 'group_name':'Drifter Knight', 'text': '<i>One look and it pull you right in.</i><br /><br />Drop chance: 1/15.'},
'Fleshy Armor': {'type': 'hide', 'group_name':'Drifter Knight', 'text': '<i>Surprisingly durable, tastes like hagfish.</i><br /><br />Drop chance: 4/15.'},
'Petrified Plate': {'type': 'bone/scrap', 'group_name':'Drifter Knight', 'text': '<i>A thousands years of heat in one plate.</i><br /><br />Drop chance: 2/15.'},
'Silken Skin': {'type': 'organ/slik', 'group_name':'Drifter Knight', 'text': '<i>Looks fabulous in any lighting.</i><br /><br />Drop chance: 2/15.'},
'Stinging Tendrils': {'type': 'organ', 'group_name':'Drifter Knight', 'text': '<i>Hard to grasp without gloves.</i><br /><br />Drop chance: 4/15.'},
}

module.exports = {
 texts,
}
