const texts = {
'Cabled Vein (Dragon King)': {'label':'', 'type': 'organ', 'text': '<i>A dense bundle of bloody tubes.</i><br /><br />Drop chance: 2/21.'},
'Dragon Iron (Dragon King)': {'type': 'iron', 'text': '<i>It feels heavy, but when dropped, falls as slowly as a feather.</i><br /><br />Drop chance: 1/21.'},
'Hardened Ribs (Dragon King)': {'type': 'bone', 'text': '<i>Strong, flexible, and hollow.</i><br /><br />Drop chance: 1/21.'},
'Horn Fragment (Dragon King)': {'type': 'bone', 'text': '<i>Nearby speech causes them to resonate.</i><br /><br />Drop chance: 4/21.'},
'Husk (Dragon King)': {'type': 'hide', 'text': '<i>A decaying layer of former skin.</i><br /><br />Drop chance: 3/21.'},
'King\'s Claws (Dragon King)': {'type': 'bone', 'text': '<i>Disturbingly warm, and sharp enough to draw blood with a touch.</i><br /><br />Drop chance: 4/21.'},
'King\'s Tongue (Dragon King)': {'type': 'hide', 'text': '<i>Smooth, dry, and sharp.</i><br /><br />Drop chance: 1/21.'},
'Radioactive Drug (Dragon King)': {'type': 'organ/scrap', 'text': '<i>Gives off smoke with an acrid odor.</i><br /><br />Drop chance: 2/21.'},
'Veined Wing (Dragon King)': {'type': 'hide', 'text': '<i>Blood drips from it at a constant rate.</i><br /><br />Drop chance: 3/21.'},

'Beetle Horn (Dung Beetle Knight)': {'type': 'bone', 'text': '<b>Brain Stimulation</b> <i style="color:#999">(requires Scarification)</i><br />Archive and Roll <b>1d10</b>:<br /> <b style=\"color:#cc0;font-size:1.1em;\">1-4</b> - Your brain is punctured and you die.<br /> <b style=\"color:#cc0;font-size:1.1em;\">5+</b> - <i>Brain Stimulation</i> Gain the benefits of <b>Age 1</b> and <b>Age 2</b> without gaining Hunt XP. Brain Stimulation ignores the "once a lifetime" rule on the <b>Age</b> story event.<br /><br />Drop chance: 1/11.'},
'Century Fingernails (Dung Beetle Knight)': {'type': 'bone', 'text': '<i>These nails are never clipped. Instead, they are folded and hammered hundreds of times into an impossibly fine edge.</i><br /><br />Drop chance: 2/11.'},
'Century Shell (Dung Beetle Knight)': {'type': 'hide/iron', 'text': '<i>This ancient and mineral-rich armor plate is covered with razor wind scratches.</i><br /><br />You may spend this as if it were a Scarab Shell resource.<br /><br />Drop chance: 1/11.'},
'Compound Eye (Dung Beetle Knight)': {'type': 'organ/consumable', 'text': '<i>A cluster of differently colored eyes, each filled with a creamy, tangy syrup.</i><br /><br />If you have 3+ courage, you may consume and archive this to gain +3d10 insanity.<br /><br />Drop chance: 1/11.'},
'Elytra (Dung Beetle Knight)': {'type': 'bone/hide/organ', 'text': '<i>The ribbed underside of these large shells makes an ideal surface to grind weapons.</i><br /><br />A survivor may archive this to give all of their attacks in the next showdown Sharp.<br /><br />Drop chance: 1/11.'},
'Scarab Shell (Dung Beetle Knight)': {'type': 'hide', 'text': '<i>Cool and oily to the touch. Lantern light reveals a brilliant band of color dancing on its surface.</i><br /><br />Drop chance: 3/11.'},
'Scarab Wing (Dung Beetle Knight)': {'type': 'organ', 'text': '<i>When soaked in water, these vein-filled wings gain some elasticity.</i><br /><br />Drop chance: 1/11.'},
'Underplate Fungus (Dung Beetle Knight)': {'type': 'herb/hide/consumable', 'text': '<i>A corkscrew-shaped fungus that grows in the empty channels between the Dung Beetle Knight\'s armor plating.</i><br /><br />Drop chance: 1/11.'},

'Lantern Bloom (Flower Knight)': {'type': 'flower/hide', 'text': '<b>Perishable</b>.<br />You may <b>consume</b> and archive this during the showdown to gain +3 luck tokens, -1 permanent luck, and the <b>Flower Addiction</b> disorder.<br />vDrop chance: 3/14.'},
'Lantern Bud (Flower Knight)': {'type': 'flower/scrap', 'text': '<b>Perishable</b>.<br />You may <b>consume</b> and archive this during the settlement phase to gain +3 Endeavor, skip the next hunt, and gain the <b>Flower Addiction</b> disorder.<br /><br />Drop chance: 1/14.'},
'Osseous Bloom (Flower Knight)': {'type': 'flower/bone', 'text': '<b>Perishable</b>.<br />You may <b>consume</b> and archive this during the showdown to remove all your bleeding and negative attribute tokens and gain the <b>Flower Addiction</b> disorder.<br /><br />Drop chance: 5/14.'},
'Sighing Bloom (Flower Knight)': {'type': 'flower/organ', 'text': '<b>Perishable</b>.<br />You may <b>consume</b> and archive this during the showdown to gain 3 survival, 3 insanity, and the <b>Flower Addiction</b> disorder.<br /><br />Drop chance: 3/14.'},
'Warbling Bloom (Flower Knight)': {'type': 'flower/hide', 'text': '<b>Perishable</b>.<br />You may plant this during the settlement phase to archive it and gain +1 population. The survivor is born with the <b>Flower Addiction</b> disorder and a face just like the Warbling Bloom\'s.<br /><br />Drop chance: 2/14.'},

'Acid Gland (Gorm)': {'type': 'organ', 'text': '<i>Melts skin.</i><br /><br />Drop chance: 1/21.'},
'Dense Bone (Gorm)': {'type': 'bone', 'text': '<i>Sturdy.</i><br /><br />Drop chance: 2/21.'},
'Gorm Brain (Gorm)': {'type': 'organ', 'text': '<i>Shockingly small.</i><br /><br />Drop chance: 1/21.'},
'Handed Skull (Gorm)': {'type': 'bone', 'text': '<i>Incomparably dense.</i><br /><br />Drop chance: 1/21.'},
'Jiggling Lard (Gorm)': {'type': 'organ/hide', 'text': '<i>Thick, quivering mass.</i><br /><br />Drop chance: 2/21.'},
'Mammoth Hand (Gorm)': {'type': 'bone/hide/organ', 'text': '<i>An enormous, leathery glove.</i><br /><br />Drop chance: 2/21.'},
'Meaty Rib (Gorm)': {'type': 'bone/organ', 'text': '<i>Useful and delicious.</i><br /><br />Drop chance: 2/21.'},
'Milky Eye (Gorm)': {'type': 'organ', 'text': '<i>When this resource is gained, select a survivor to gain +3 insanity.<br /><br />Drop chance: 1/21.'},
'Stout Heart (Gorm)': {'type': 'organ', 'text': '<i>A titanic pump.</i><br /><br />Drop chance: 2/21.'},
'Stout Hide (Gorm)': {'type': 'hide', 'text': '<i>Touch, wrinkly skin.</i><br /><br />Drop chance: 4/21.'},
'Stout Kidney (Gorm)': {'type': 'organ', 'text': '<b>Consume</b>: archive this and roll 1d10:<br /> <b>1-5</b> - reduce your survival to 0.<br /> <b>6+<b/> - gain 10 survival.<br /><br />Drop chance: 2/21.'},
'Stout Vertebrae (Gorm)': {'type': 'bone', 'text': '<i>Hefty and intricately joined.</i><br /><br />Drop chance: 1/21.'},

'Bird Beak (Phoenix)': {'type': 'bone', 'text': '<i>Surprisingly toothy.</i><br /><br />Drop chance: 1/24.'},
'Black Skull (Phoenix)': {'type': 'iron/skull/bone', 'text': '<i>Aged to perfection.</i><br /><br />Drop chance: 1/24.'},
'Hollow Wing Bones (Phoenix)': {'type': 'bone', 'text': '<i>Delicate and finely balanced.</i><br /><br />Drop chance: 3/24.'},
'Muculent Droppings (Phoenix)': {'type': 'organ', 'text': '<i>Delicately scented, papery husk.</i><br /><br />Drop chance: 3/24.'},
'Phoenix Eye (Phoenix)': {'type': 'organ/scrap', 'text': '<i>Filled with a thick, metallic liquid.</i><br /><br />Drop chance: 1/24.'},
'Phoenix Finger (Phoenix)': {'type': 'bone', 'text': 'When you gain this, a survivor of your choice gains +3 insanity.<br /><br />Drop chance: 2/24.'},
'Phoenix Whisker (Phoenix)': {'type': 'hide', 'text': '<i>Silky, yet robust.</i><br /><br />Drop chance: 1/24.'},
'Pustules (Phoenix)': {'type': 'organ/consumable', 'text': '<i>The aroma is tempting.</i><br /><br />Drop chance: 2/24.'},
'Rainbow Droppings (Phoenix)': {'type': 'organ/consumable', 'text': '<b>Consume</b>: Archive this and roll 1d10:<br /> <b>1-6</b> - your heart explodes, killing you instantly.<br /><b>7+</b> - gain +1 permanent speed.<br /><br />Drop chance: 1/24.'},
'Shimmering Halo (Phoenix)': {'type': 'organ', 'text': '<i>Curiously heavy.</i><br /><br />Drop chance: 1/24.'},
'Small Feathers (Phoenix)': {'type': 'hide', 'text': '<i>Soft interior with razor sharp edges.</i><br /><br />Drop chance: 3/24.'},
'Small Hand Parasites (Phoenix)': {'type': 'organ', 'text': '<i>Still wriggling.</i><br /><br />Drop chance: 1/24.'},
'Tail Feathers (Phoenix)': {'type': 'hide', 'text': '<i>Lighter than air.</i><br /><br />Drop chance: 3/24.'},
'Wishbone (Phoenix)': {'type': 'bone', 'text': '<i>A delicate bone with a strange aura.</i><br /><br />Drop chance: 1/24.'},

'Beast Steak (Screaming Antelope)': {'type': 'organ/consumable', 'text': '<i>Shockingly appetizing.</i><br /><br />Drop chance: 2/16.'},
'Bladder (Screaming Antelope)': {'type': 'organ/consumable', 'text': '<i>Smells like urine.</i><br /><br />Drop chance: 1/16.'},
'Large Flat Tooth (Screaming Antelope)': {'type': 'bone', 'text': '<i>It\'s surface is rough and bumpy.</i><br /><br />When you gain this, a survivor of your choice gains +1 insanity.<br /><br />Drop chance: 2/16.'},
'Muscly Gums (Screaming Antelope)': {'type': 'organ/consumable', 'text': '<i>Difficult to pry apart.</i><br /><br />Drop chance: 1/16.'},
'Pelt (Screaming Antelope)': {'type': 'hide', 'text': '<i>Coarse and warm.</i><br /><br />Drop chance: 4/16.'},
'Screaming Brain (Screaming Antelope)': {'type': 'organ/consumable', 'text': '<b>Consume</b>: Archive this and gain survival up to the current limit.<br /><br />Drop chance: 1/16.'},
'Shank Bone (Screaming Antelope)': {'type': 'bone', 'text': '<i>Strangely jointed.</i><br /><br />Drop chance: 4/16.'},
'Spiral Horn (Screaming Antelope)': {'type': 'bone', 'text': '<i>Moans balefully when blown.</i><br /><br />Drop chance: 1/16.'},

'Arachnid Heart (Spidicules)': {'type': 'organ', 'text': '<i>Cold to the touch, even when freshly removed.</i><br /><br />Drop chance: 1/14.'},
'Chitin (Spidicules)': {'type': 'hide', 'text': '<i>A flaky, bitter-smelling husk.</i><br /><br />Drop chance: 1/14.'},
'Exoskeleton (Spidicules)': {'type': 'hide', 'text': '<i>Malleable, interlocking plates.</i><br /><br />Drop chance: 1/14.'},
'Eyeballs (Spidicules)': {'type': 'organ', 'text': '<i>Each points in a different direction.</i><br /><br />Drop chance: 1/14.'},
'Large Appendage (Spidicules)': {'type': 'bone', 'text': '<i>Could come in handy.</i><br /><br />Drop chance: 2/14.'},
'Serrated Fangs (Spidicules)': {'type': 'bone', 'text': '<b>Razor Push-ups</b> <i style="color:#999">(requires Nightmare Training)</i> - Roll 1d10<br /> <b>1-3</b> - Gain random disorder.<br /> <b>4+</b> - Gain +1 permanent Strength. <i>The fangs are crushed;</i> archive this card.<br /><br />Drop chance: 1/14.'},
'Small Appendages (Spidicules)': {'type': 'hide', 'text': '<i>The inner hands look surprisingly human.</i><br /><br />Drop chance: 2/14.'},
'Spinnerets (Spidicules)': {'type': 'organ/scrap', 'text': '<i>More complex than any device.</i><br /><br />Drop chance: 1/14.'},
'Stomach (Spidicules)': {'type': 'organ', 'text': '<b>Consume</b>: Archive this card to gain +1 Hunt XP.<br /><br />Drop chance: 1/14.'},
'Thick Web Silk (Spidicules)': {'type': 'silk/hide', 'text': '<i>Impossible to pierce.</i><br /><br />Drop chance: 1/14.'},
'Unlaid Eggs (Spidicules)': {'type': 'organ/consumable', 'text': 'During the settlement phase, you may <b>consume</b> and archive these delicious little eggs to gain 10 survival.<br /><br />Drop chance: 1/14.'},
'Venom Sac (Spidicules)': {'type': 'organ/consumable', 'text': '<b>Consume</b>: Archive this card and roll 1d10.<br /> <b>1-5</b> - you die instantly.<br /> <b>6+</b> - gain the <b>Death Touch</b> Secret Fighting Art.<br /><br />Drop chance: 1/14.'},

'Black Lens (Sunstalker)': {'type': 'organ', 'text': '<i>These eyes are filled with a savory, gluey substance that dries when exposed to air.</i><br /><br />Drop chance: 1/24.'},
'Brain Root (Sunstalker)': {'type': 'organ', 'text': '<i>The strands of the root are strong and elastic. The meat on top is useless.</i><br /><br />Drop chance: 1/24.'},
'Cycloid Scales (Sunstalker)': {'type': 'hide', 'text': '<i>Extremely reflective and colorful.</i><br /><br />Drop chance: 5/24.'},
'Fertility Tentacle (Sunstalker)': {'type': 'organ', 'text': '<i>This tube-like appendage has a cavity at the base that stores eggs.</i><br /><br />Drop chance: 1/24.'},
'Huge Sunteeth (Sunstalker)': {'type': 'bone', 'text': '<i>These tough but light teeth are made of hundreds of thin layers of bone, separated by rows of dicot stems.</i><br /><br />Drop chance: 3/24.'},
'Inner Shadow Skin (Sunstalker)': {'type': 'hide', 'text': '<i>This soft, yet rubbery material blocks light.</i><br /><br />Drop chance: 1/24.'},
'Prismatic Gills (Sunstalker)': {'type': 'organ', 'text': '<i>When you gain this, gain the Emotionless disorder. The gills emit a fuzzy color trail.</i><br /><br />Drop chance: 1/24.'},
'Shadow Ink Gland (Sunstalker)': {'type': 'organ', 'text': '<i>The ink can be used to paint shadows that vanish in lantern light.</i><br /><br />Drop chance: 1/24.'},
'Shadow Tentacles (Sunstalker)': {'type': 'organ/hide', 'text': '<i>When you gain this during the hunt or showdown, return it to the resource deck and draw again if any survivors are <b>blind</b>.<br /><br />Drop chance: 2/24.'},
'Shark Tongue (Sunstalker)': {'type': 'organ', 'text': '<i>So slippery that it\'s hard to hold!</i><br /><br />Drop chance: 1/24.'},
'Small Sunteeth (Sunstalker)': {'type': 'bone', 'text': '<i>Unlike the large sunteeth, these are extremely sharp and clean.</i><br /><br />Drop chance: 3/24.'},
'Stink Lung (Sunstalker)': {'type': 'organ', 'text': '<i>When squeezed, a funny noise emerges followed by a tantalizing aroma.</i><br /><br />Drop chance: 1/24.'},
'Sunshark Blubber (Sunstalker)': {'type': 'organ', 'text': '<i>When inflated with air, this blubber gently floats.</i><br /><br />Drop chance: 1/24.'},
'Sunshark Bone (Sunstalker)': {'type': 'bone', 'text': '<i>The center is filled with water.</i><br /><br />Drop chance: 1/24.'},
'Sunshark Fin (Sunstalker)': {'type': 'bone/hide', 'text': '<i>Removing the slimy hands reveals a curable, viscous substance.</i><br /><br />Drop chance: 1/24.'},

'Curious Hand (White Lion)': {'image':'true', 'type': 'hide', 'text': ' <i>Holding this fills you with sadness.</i><br /><br />When you gain this, a random survivor gains +1 insanity.<br /><br />Drop chance: 1/19.'},
'Eye of Cat (White Lion)': {'image':'true', 'type': 'organ/consumable', 'text': '<i>A perfectly preserved eye.</i><br /><br />Drop chance: 1/19.'},
'Golden Whiskers (White Lion)': {'image':'true', 'type': 'organ', 'text': '<i>These whiskers are tough!</i><br /><br />Drop chance: 1/19.'},
'Great Cat Bones (White Lion)': {'image':'true', 'type': 'bone', 'text': '<i>Strong and surprisingly light.</i><br /><br />Drop chance: 4/19.'},
'Lion Claw (White Lion)': {'image':'true', 'type': 'bone', 'text': '<i>A razor-sharp, retractable claw.</i><br /><br />Drop chance: 3/19.'},
'Lion Tail (White Lion)': {'image':'true', 'type': 'hide', 'text': '<i>It\'s surprisingly heavy.</i><br /><br />Drop chance: 1/19.'},
'Lion Testes (White Lion)': {'image':'true', 'type': 'organ/consumable', 'text': '<i>A hefty pair of nuts.</i><br /><br />Drop chance: 1/19.'},
'Shimmering Mane (White Lion)': {'image':'true', 'type': 'hide', 'text': ' <i>It shimmers in the lantern light.</i><br /><br />Archive this to gain 2 basic hide resources.<br /><br />Drop chance: 1/19.'},
'Sinew (White Lion)': {'image':'true', 'type': 'organ', 'text': '<i>These stringy guts are quite useful.</i><br /><br />Drop chance: 2/19.'},
'White Fur (White Lion)': {'image':'true', 'type': 'hide', 'text': '<i>Luxurious and soft to the touch.</i><br /><br />Drop chance: 4/19.'},

'qqq (Basic)': {'label': '??? (Basic)', 'image': 'true', 'type': 'organ/bone/hide/consumable', 'text': '<i>You have no idea what monster bit this is.</i><br /><br />Can be used as a bone, organ, or hide!<br /><br />Drop chance: 2/21.'},
'Broken Lantern (Basic)': {'image': 'true', 'type': 'scrap', 'text': '<i>Remains of an extinguished lantern.</i><br /><br />Drop chance: 2/21.'},
'Love Juice (Basic)': {'image': 'true', 'type': 'organ/consumable', 'text': 'During the settlement phase, you may archive this to triggrer <b>Intimacy</b> story event. Nominated survivors must be able to consume.<br /><br />Drop chance: 2/21.'},
'Monster Bone (Basic)': {'image': 'true', 'type': 'bone', 'text': '<i>A bone suitable for crafting.</i><br /><br />Drop chance: 4/21.'},
'Monster Hide (Basic)': {'image': 'true', 'type': 'hide', 'text': '<i>The skin of a beast.</i><br /><br />Drop chance: 7/21.'},
'Monster Organ (Basic)': {'image': 'true', 'type': 'organ/consumable', 'text': 'If you <b>consume</b> this, archive this card. Roll 1d10:<br /> <b>6+</b> -  you contract a parasite. Archive all consumable gear in your grid now.<br /><br />Drop chance: 3/21.'},
'Skull (Basic)': {'image': 'true', 'type': 'bone', 'text': 'When you gain this, a survivor of your choice gains +1 insanity.<br /><br />Drop chance: 1/21.'},

'1,000 Year Sunspot (Sunstalker, Strange)': {'type': 'bone/organ', 'text': ''},
'3,000 Year Sunspot (Sunstalker, Strange)': {'type': 'bone/organ/scrap', 'text': ''},
'Active Thyroid (Gorm, Strange)': {'type': 'organ/consumable', 'text': ''},
'Black Lichen (Strange)': {'type': 'bone/organ/hide/consumable/other', 'text': ''},
'Blistering Plasma Fruit (Lonely Tree, Strange)': {'type': 'organ/consumable', 'text': ''},
'Bugfish (Sunstalker, Strange)': {'type': 'fish/organ', 'text': ''},
'Canopic Jar (Lion God, Strange)': {'type': 'organ/scrap', 'text': ''},
'Cocoon Membrane (Strange)': {'type': 'organ/other', 'text': ''},
'Crimson Vial (Manhunter, Strange)': {'type': 'iron/consumable', 'text': ''},
'Crystal Sword Mold (Slenderman, Strange)': {'type': 'scrap/iron', 'text': ''},
'Dark Water (Slenderman, Strange)': {'type': 'other', 'text': ''},
'Drifting Dream Fruit (Lonely Tree, Strange)': {'type': 'consumable', 'text': ''},
'Elder Cat Teeth (White Lion, Strange)': {'type': 'bone', 'text': ''},
'Fresh Acanthus (Strange)': {'type': 'herb', 'text': ''},
'Gormite (Gorm, Strange)': {'type': 'scrap/iron', 'text': ''},
'Hagfish (Sunstalker, Strange)': {'type': 'fish/bone/hide', 'text': ''},
'Iron (Strange)': {'type': 'scrap/iron', 'text': ''},
'Jagged Marrow Fruit (Lonely Tree, Strange)': {'type': 'bone/scrap/consumable', 'text': ''},
'Jowls (Sunstalker, Strange)': {'type': 'fish/iron', 'text': ''},
'Lantern Tube (Strange)': {'type': 'organ/scrap', 'text': ''},
'Leather (Strange)': {'type': 'hide/leather', 'text': ''},
'Legendary Horns (Screaming Antelope, Strange)': {'type': 'bone/scrap', 'text': ''},
'Lonely Fruit (Lonely Tree, Strange)': {'type': 'consumable', 'text': ''},
'Old Blue Box (Lion God, Strange)': {'type': 'scrap', 'text': ''},
'Perfect Crucible (Strange)': {'type': 'iron', 'text': ''},
'Phoenix Crest (Phoenix, Strange)': {'type': 'organ', 'text': ''},
'Pituitary Gland (Dragon King, Strange)': {'type': 'organ', 'text': ''},
'Porous Flesh Fruit (Lonely Tree, Strange)': {'type': 'hide/consumable', 'text': ''},
'Preserved Caustic Dung (Dung Beetle Knight, Strange)': {'type': 'organ/consumable/dung', 'text': ''},
'Pure Bulb (Gorm, Strange)': {'type': '', 'text': 'organ'},
'Radiant Heart (Dragon King, Strange)': {'type': 'organ', 'text': ''},
'Red Vial (Manhunter, Strange)': {'type': 'consumable', 'text': ''},
'Salt (Sunstalker, Strange)': {'type': 'salt', 'text': ''},
'Scell (Dung Beetle Knight, Strange)': {'type': 'organ/consumable', 'text': ''},
'Sarcophagus (Lion God, Strange)': {'type': 'iron', 'text': ''},
'Second Heart (Screaming Antelope, Strange)': {'type': 'organ/bone', 'text': ''},
'Shining Liver (Dragon King, Strange)': {'type': 'organ', 'text': ''},
'Silken Nervous System (Spidicules, Strange)': {'type': 'organ', 'text': ''},
'Silver Urn (Lion God, Strange)': {'type': 'bone/scrap', 'text': ''},
'Stomach Lining (Gorm, Strange)': {'type': 'organ', 'text': ''},
'Sunstones (Sunstalker, Strange)': {'type': 'bone', 'text': ''},
'Triptych (Lion God, Strange)': {'type': 'hide/scrap', 'text': ''},
'Web Silk (Spidicules, Strange)': {'type': 'silk', 'text': ''},

'Metal Face (Strange)': {'type':'scrap', 'text': '<i>A magnetic force emanates from the metal.</i><br /><br />During the settlement phase, you may archive 3 <b>Metal Face</b> strange resources to add 1 <b>Storm Helmet</b> rare gear to settlement storage.'}
}

module.exports = {
 texts,
}
